/*
 Stickyfill ? `position: sticky` polyfill
 v. 2.0.3 | https://github.com/wilddeer/stickyfill
 MIT License
*/
(function(g,l){function p(a,b){for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e])}function v(a){for(var b=0;a;)b+=a.offsetTop,a=a.offsetParent;return b}function w(){function a(){g.pageXOffset!=h.left?(h.top=g.pageYOffset,h.left=g.pageXOffset,m.refreshAll()):g.pageYOffset!=h.top&&(h.top=g.pageYOffset,h.left=g.pageXOffset,f.forEach(function(b){return b._recalcPosition()}))}function b(){e=setInterval(function(){f.forEach(function(b){return b._fastCheck()})},500)}a();g.addEventListener("scroll",a);g.addEventListener("resize",
m.refreshAll);g.addEventListener("orientationchange",m.refreshAll);var e=void 0,c=void 0,d=void 0;"hidden"in l?(c="hidden",d="visibilitychange"):"webkitHidden"in l&&(c="webkitHidden",d="webkitvisibilitychange");d?(l[c]||b(),l.addEventListener(d,function(){l[c]?clearInterval(e):b()})):b()}var x=function(){function a(b,a){for(var e=0;e<a.length;e++){var d=a[e];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(b,d.key,d)}}return function(b,e,c){e&&a(b.prototype,
e);c&&a(b,c);return b}}(),t=!1;g.getComputedStyle?function(){var a=l.createElement("div");["","-webkit-","-moz-","-ms-"].some(function(b){try{a.style.position=b+"sticky"}catch(e){}return""!=a.style.position})&&(t=!0)}():t=!0;var y="undefined"!==typeof ShadowRoot,h={top:null,left:null},f=[],r=function(){function a(b){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");if(!(b instanceof HTMLElement))throw Error("First argument must be HTMLElement");if(f.some(function(a){return a._node===
b}))throw Error("Stickyfill is already applied to this node");this._node=b;this._stickyMode=null;this._active=!1;f.push(this);this.refresh()}x(a,[{key:"refresh",value:function(){if(!t&&!this._removed){this._active&&this._deactivate();var b=this._node,a=getComputedStyle(b),c=a.top,d=a.display,f=a.marginTop,h=a.marginBottom,m=a.marginLeft,r=a.marginRight;a=a.cssFloat;if(!isNaN(parseFloat(c))&&"table-cell"!=d&&"none"!=d){this._active=!0;d=b.parentNode;var n=y&&d instanceof ShadowRoot?d.host:d,k=b.getBoundingClientRect(),
u=n.getBoundingClientRect(),q=getComputedStyle(n);this._parent={node:n,styles:{position:n.style.position},offsetHeight:n.offsetHeight};this._offsetToWindow={left:k.left,right:l.documentElement.clientWidth-k.right};this._offsetToParent={top:k.top-u.top-(parseFloat(q.borderTopWidth)||0),left:k.left-u.left-(parseFloat(q.borderLeftWidth)||0),right:-k.right+u.right-(parseFloat(q.borderRightWidth)||0)};this._styles={position:b.style.position,top:b.style.top,bottom:b.style.bottom,left:b.style.left,right:b.style.right,
width:b.style.width,marginTop:b.style.marginTop,marginLeft:b.style.marginLeft,marginRight:b.style.marginRight};c=parseFloat(c)||0;this._limits={start:k.top+g.pageYOffset-c,end:u.top+g.pageYOffset+n.offsetHeight-(parseFloat(q.borderBottomWidth)||0)-b.offsetHeight-c-(parseFloat(h)||0)};c=q.position;"absolute"!=c&&"relative"!=c&&(n.style.position="relative");this._recalcPosition();c=this._clone={};c.node=l.createElement("div");p(c.node.style,{width:k.right-k.left+"px",height:k.bottom-k.top+"px",marginTop:f,
marginBottom:h,marginLeft:m,marginRight:r,cssFloat:a,padding:0,border:0,borderSpacing:0,fontSize:"1em",position:"static"});d.insertBefore(c.node,b);c.docOffsetTop=v(c.node)}}}},{key:"_recalcPosition",value:function(){if(this._active&&!this._removed){var a=h.top<=this._limits.start?"start":h.top>=this._limits.end?"end":"middle";if(this._stickyMode!=a){switch(a){case "start":p(this._node.style,{position:"absolute",left:this._offsetToParent.left+"px",right:this._offsetToParent.right+"px",top:this._offsetToParent.top+
"px",bottom:"auto",width:"auto",marginLeft:0,marginRight:0,marginTop:0});break;case "middle":p(this._node.style,{position:"fixed",left:this._offsetToWindow.left+"px",right:this._offsetToWindow.right+"px",top:this._styles.top,bottom:"auto",width:"auto",marginLeft:0,marginRight:0,marginTop:0});break;case "end":p(this._node.style,{position:"absolute",left:this._offsetToParent.left+"px",right:this._offsetToParent.right+"px",top:"auto",bottom:0,width:"auto",marginLeft:0,marginRight:0})}this._stickyMode=
a}}}},{key:"_fastCheck",value:function(){this._active&&!this._removed&&(1<Math.abs(v(this._clone.node)-this._clone.docOffsetTop)||1<Math.abs(this._parent.node.offsetHeight-this._parent.offsetHeight))&&this.refresh()}},{key:"_deactivate",value:function(){var a=this;this._active&&!this._removed&&(this._clone.node.parentNode.removeChild(this._clone.node),delete this._clone,p(this._node.style,this._styles),delete this._styles,f.some(function(b){return b!==a&&b._parent&&b._parent.node===a._parent.node})||
p(this._parent.node.style,this._parent.styles),delete this._parent,this._stickyMode=null,this._active=!1,delete this._offsetToWindow,delete this._offsetToParent,delete this._limits)}},{key:"remove",value:function(){var a=this;this._deactivate();f.some(function(b,c){if(b._node===a._node)return f.splice(c,1),!0});this._removed=!0}}]);return a}(),m={stickies:f,Sticky:r,addOne:function(a){if(!(a instanceof HTMLElement))if(a.length&&a[0])a=a[0];else return;for(var b=0;b<f.length;b++)if(f[b]._node===a)return f[b];
return new r(a)},add:function(a){a instanceof HTMLElement&&(a=[a]);if(a.length){for(var b=[],e=function(c){var d=a[c];if(!(d instanceof HTMLElement))return b.push(void 0),"continue";if(f.some(function(a){if(a._node===d)return b.push(a),!0}))return"continue";b.push(new r(d))},c=0;c<a.length;c++)e(c);return b}},refreshAll:function(){f.forEach(function(a){return a.refresh()})},removeOne:function(a){if(!(a instanceof HTMLElement))if(a.length&&a[0])a=a[0];else return;f.some(function(b){if(b._node===a)return b.remove(),
!0})},remove:function(a){a instanceof HTMLElement&&(a=[a]);if(a.length)for(var b=function(b){var c=a[b];f.some(function(a){if(a._node===c)return a.remove(),!0})},e=0;e<a.length;e++)b(e)},removeAll:function(){for(;f.length;)f[0].remove()}};t||w();"undefined"!=typeof module&&module.exports?module.exports=m:g.Stickyfill=m})(window,document);
