var _version=2;"EVENTSTACK"in window||(window.EVENTSTACK=[]);var objScroll=new Scroll,objPerformance=new Performance,objPing=new Ping,objTools=new Tools,objPWConfig=new pwConfig,nowtime=Math.floor(new Date/1E3),tmpInt=Number(String(Math.random()).slice(2)),hit_id=Number(String(nowtime+tmpInt).slice(0,9)),pingTimerID=0,objEvents=new Events,objEventClick=new EventClick(objEvents),objEventScroll=new EventScroll(objEvents);objEventClick.titleVerClick();objEventClick.recommendAlg();var objEventModel=new EventModel;
objEventModel.subscribe("scroll","main_ab_title",objEventScroll.ObserverABTitle);objEventModel.subscribe("scroll","article_infinity",objEventScroll.ObserverInfinity);objEventModel.subscribe("scroll","article_rcmd_under_article",objEventScroll.ObserverRcmdUnderArticle);objEventModel.subscribe("click","main_ab_title",objEventScroll.ObserverTitleVer);objEventModel.subscribe("click","article_rcmd_under_article",objEventScroll.ObserverRecommendAlg);objEventModel.import(window.EVENTSTACK);
window.EVENTSTACK=objEventModel;window.onload=function(){objTools.hashchangeHandler()};document.addEventListener("DOMContentLoaded",objScroll.setPageHight);document.addEventListener("scroll",objScroll.scroll);window.addEventListener("hashchange",objTools.hashchangeHandler,!1);
function Scroll(){function b(b){for(var g=0;b;)g+=parseFloat(b.offsetTop),b=b.offsetParent;return Math.round(g)}var e=this,n=0,c=0,h=[10,20,30,40,50,60,70,80,90,100],g=h.length,v=null,z=0;this.scrollResult=0;this.setPageHight=function(){n=e.getPageHight()};this.getPageHight=function(){var g=Math.max(document.body&&document.body.scrollHeight?document.body.scrollHeight:0,document.documentElement&&document.documentElement.scrollHeight?document.documentElement.scrollHeight:0,document.body&&document.body.offsetHeight?
document.body.offsetHeight:0,document.documentElement&&document.documentElement.offsetHeight?document.documentElement.offsetHeight:0,document.body&&document.body.clientHeight?document.body.clientHeight:0,document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:0),h,e=0;if(window.jQuery){var c=$("div.mia-analytics");$("div").is(".mia-analytics")&&(h=c.offset().top,c=c.outerHeight(),e=Math.round(h+c))}else(e=wa("mia-analytics"))&&e[0]&&"object"==typeof e&&
(e=e[0],h=b(e),c=e.clientHeight),e=h+c;return(h=e)&&10<h?h:g};this.scroll=function(){c=window.pageYOffset||document.documentElement.scrollTop;c+=window.innerHeight;if(0<n){var b=Math.ceil(100/(n/c));b>z&&(z=b,clearTimeout(v),v=setTimeout(I,100))}};this.longArticle=function(){var b=this.getPageHight(),b=Math.floor((b-100)/window.innerHeight);0>b&&(b=0);return b};this.visualization=function(){console.log("Analytics GO");var e=document.getElementById("analytics-scala");e&&"object"==typeof e&&e.parentNode.removeChild(e);
e=wa("mia-analytics")[0];if(!e||"object"!=typeof e&&10>=e.offsetHeight)e=document.body;console.log("Canvas GO");var c=document.createElement("canvas"),n=c.getContext("2d"),w=b(e);console.log("TOP",w);c.height=e.offsetHeight+35;c.width=document.body.offsetWidth;c.id="analytics-scala";c.style.position="absolute";c.style.top=w+"px";c.style.zIndex="9999";document.body.appendChild(c);n.strokeStyle="#ff0000";n.fillStyle="#ff0000";n.font="bold 30pt Arial";n.moveTo(0,1);n.lineTo(c.width,0);n.fillText("0%",
0,35);n.stroke();for(w=0;w<g;w++){var v=Math.ceil(h[w]/100*e.offsetHeight);n.moveTo(0,v);n.lineTo(c.width,v);n.fillText(h[w]+"%",0,v+35);n.stroke()}};var I=function(){var b=0;if(e.getPageHight()!=n)return e.setPageHight(),!1;if(z>e.scrollResult)for(var c=0;c<=g;c++)if(z>=h[c])b=h[c];else break;0<b&&(e.scrollResult=b)},wa=function(b){var e=[];if(document.getElementsByClassName)e=document.getElementsByClassName(b);else{var g=document.body.getElementsByTagName("div"),h=g.length,e=[],c;for(c=0;c<h;c+=
1)-1!=g[c].className.search("\\b"+b+"\\b")&&e.push(g[c])}return e}}
function Performance(){this.params={navigation_type:0,timing_full_response:0,timing_dns:0,timing_download:0,timing_waiting:0,timing_request:0};this.getParams=function(){performance&&"object"==typeof performance&&performance.timing&&(this.params={navigation_type:performance.navigation.type?performance.navigation.type:255,timing_full_response:performance.timing.responseEnd-performance.timing.navigationStart,timing_dns:performance.timing.domainLookupEnd-performance.timing.domainLookupStart,timing_download:performance.timing.responseEnd-
performance.timing.responseStart,timing_waiting:performance.timing.responseStart-performance.timing.requestStart,timing_request:performance.timing.requestStart-performance.timing.connectEnd});return this.params}}
function Events(){this.request={idsite:"",url:"",_id:"",_idts:"",localtime:Math.round((new Date).getTime()/1E3),h_id:hit_id,r:"",events:window.EVENTSTACK};this.setRequestVar=function(b,e){if("events"==b)return console.log("[Events] Variable Events reserved"),!1;this.request[b]=e;return!0};this.addEvent=function(b,e){if(!b)return console.log("[Events] The event is not added, name empty!"),!1;if("object"!=typeof e)return console.log("[Events] The event is not added, params must be an object!"),!1;e.etype=
b;this.request.events.push(e);return!0};this.getReguest=function(){this.request.r=String(Math.random()).slice(2,8);var b=JSON.parse(JSON.stringify(this.request));this.request.events=[];return b}}
function EventClick(b){var e=(new Meta).getMeta();this.ObserverTitleVer=function(e,c,h){b.addEvent("click",{ectgry:"title_ver",elabel:"article_id"in h?h.article_id:"",srcaid:"main",vstr:"hash"in h?h.hash:"",v2str:"algorithm"in h?h.algorithm:""})};this.ObserverRecommendAlg=function(e,c,h){b.addEvent("click",{ectgry:"recommend",elabel:"article_id"in h?h.article_id:"",srcaid:"source_aid"in h?h.source_aid:"",v2str:"algorithm"in h?h.algorithm:""})};this.titleVerClick=function(){e&&"title_ver"in e&&b.addEvent("click",
{ectgry:"ab_title",elabel:"article_id"in e?e.article_id:"",vstr:"title_ver"in e?e.title_ver:"",v2str:"title_alg"in e?e.title_alg:""})};this.recommendAlg=function(){e&&"rcmd_alg"in e&&b.addEvent("click",{ectgry:"recommend",elabel:"article_id"in e?e.article_id:"",vstr:"",v2str:"rcmd_alg"in e?e.rcmd_alg:""})}}
function EventScroll(b){(new Meta).getMeta();var e=null;this.ObserverABTitle=function(e,c,h){b.addEvent("scroll",{ectgry:"ab_title",elabel:"article_id"in h?h.article_id:"",srcaid:"main",vstr:"hash"in h?h.hash:"",v2str:"algorithm"in h?h.algorithm:""})};this.ObserverInfinity=function(n,c,h){var g=1E3*parseInt(.041*("textlength"in h?h.textlength:100)+5),v={ectgry:"recommend",elabel:"article_id"in h?h.article_id:"",srcaid:"source_aid"in h?h.source_aid:"",vstr:"infinityscroll",v2str:"algorithm"in h?h.algorithm:
""};(new Promise(function(c,h){e||clearTimeout(e);e=setTimeout(function(){b.addEvent("read",v);c()},g)})).then().catch(function(b){console.error("Event model error: "+b)});return!0};this.ObserverRcmdUnderArticle=function(e,c,h){b.addEvent("doscroll",{ectgry:"recommend",srcaid:"article_id"in h?h.article_id:"",vstr:"underpage",v2str:"algorithm"in h?h.algorithm:"",vlui64:"article_block_ids"in h?h.article_block_ids:[]})}}
function Tools(){this.serialize=function(b,e){var n=[],c;for(c in b)if(b.hasOwnProperty(c)){var h=e?e+"["+c+"]":c,g=b[c];n.push("object"==typeof g?this.serialize(g,h):h+"="+g)}return n.join("&")};this.hashchangeHandler=function(){var b=window.location.hash;b&&(b=b.split("#"),b[1]&&"analytics"==b[1]&&objScroll.visualization())}}
function Ping(){this.timeoutActivityStage=60;this.lastActivity=Math.floor(new Date/1E3);this.activityStage=1;this.getCurrentNum=function(){var b=Math.floor(new Date/1E3);b-this.lastActivity>this.timeoutActivityStage&&255>this.activityStage&&this.activityStage++;this.lastActivity=b;return this.activityStage}}
function Meta(){document.querySelectorAll(".ab__testing-info");this.getMeta=function(){var b=[],e=document.getElementsByTagName("meta"),n;for(n in e){var c=e[n];"object"==typeof c&&"getAttribute"in c&&c.getAttribute("name")&&-1<c.getAttribute("name").indexOf("analytics:")&&(b[c.getAttribute("name").split(":")[1]]=c.getAttribute("content"));"object"==typeof c&&"getAttribute"in c&&c.getAttribute("property")&&-1<c.getAttribute("property").indexOf("analytics:")&&(b[c.getAttribute("property").split(":")[1]]=
c.getAttribute("content"))}return b}}
function measureLoadPage(){this.get=function(b){var e={sum:{}},n=["img","css","script"],c=window.location.hostname;b=b?b:new RegExp("cdn(\\d+).img."+c);if(void 0!=window.performance.getEntries){c=window.performance.getEntries();for(i=0;i<c.length;i+=1){var h=c[i],g="name"in h?h.name:"",v="initiatorType"in h?h.initiatorType:"",z=this._getSize(h),h="duration"in h?h.duration:0;g.match(b)&&(g=n.indexOf(v),0<=g&&(g=n[g],g in e||(e[g]=[]),g in e.sum||(e.sum[g]={size:0,duration:0,count:0}),0<h&&(e[g].push({size:z,
duration:h}),e.sum[g].size+=z,e.sum[g].duration+=Math.floor(h),e.sum[g].count+=1)))}return e}};this._getSize=function(b){var e=0;"decodedBodySize"in b&&0<b.decodedBodySize?e=b.decodedBodySize:"encodedBodySize"in b&&0<b.encodedBodySize?e=b.encodedBodySize:"transferSize"in b&&0<b.transferSize&&(e=b.transferSize);return e}}
function EventModel(){this._subscribers={};this._events=[];this.push=function(b){if(3==b.length){var e=this;this._events.push(b);(new Promise(function(b,c){setTimeout(function(){!0===e._notify()?b():c()},0)})).then().catch(function(b){console.error("Event model error: "+b)});return!0}console.error("Event model: length array size is not 3");return!1};this.import=function(b){b&&(this._events=this._events.concat(b),this._notify());return!0};this.subscribe=function(b,e,n){b in this._subscribers||(this._subscribers[b]=
{});e in this._subscribers[b]||(this._subscribers[b][e]=[]);this._subscribers[b][e].push(n);return!0};this.unsubscribe=function(b,e){delete this._subscribers[b][e]};this._notify=function(){for(var b=this._events.length,e=0;e<b;e++){var n=this._events.shift();if(3==n.length){var c=[],h=n[0],g=n[1],n=n[2];if(h in this._subscribers&&(g in this._subscribers[h]||"*"in this._subscribers[h])){g in this._subscribers[h]&&(c=this._subscribers[h][g]);"*"in this._subscribers[h]&&(c=c.concat(this._subscribers[h]["*"]));
for(var v=0;v<c.length;v++)if(c[v])c[v](h,g,n)}}else console.error("Event model: length array size is not 3")}return!0}}function pwConfig(){this._config={};this.get=function(b){return b?b in this._config?this._config[b]:!1:this._config};this.set=function(b,e){this._config[b]=e}}"object"!==typeof JSON2&&(JSON2={});
(function(){function b(b){return 10>b?"0"+b:b}function e(b){h.lastIndex=0;return h.test(b)?'"'+b.replace(h,function(b){var e=z[b];return"string"===typeof e?e:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function n(c,h){var p,U,w,z,M=g,N,t=h[c];t&&"object"===typeof t&&(p=t,w=Object.prototype.toString.apply(p),t="[object Date]"===w?isFinite(p.valueOf())?p.getUTCFullYear()+"-"+b(p.getUTCMonth()+1)+"-"+b(p.getUTCDate())+"T"+b(p.getUTCHours())+":"+b(p.getUTCMinutes())+":"+b(p.getUTCSeconds())+
"Z":null:"[object String]"===w||"[object Number]"===w||"[object Boolean]"===w?p.valueOf():"[object Array]"!==w&&"function"===typeof p.toJSON?p.toJSON(c):p);"function"===typeof I&&(t=I.call(h,c,t));switch(typeof t){case "string":return e(t);case "number":return isFinite(t)?String(t):"null";case "boolean":case "null":return String(t);case "object":if(!t)return"null";g+=v;N=[];if("[object Array]"===Object.prototype.toString.apply(t)){z=t.length;for(p=0;p<z;p+=1)N[p]=n(p,t)||"null";w=0===N.length?"[]":
g?"[\n"+g+N.join(",\n"+g)+"\n"+M+"]":"["+N.join(",")+"]";g=M;return w}if(I&&"object"===typeof I)for(z=I.length,p=0;p<z;p+=1)"string"===typeof I[p]&&(U=I[p],(w=n(U,t))&&N.push(e(U)+(g?": ":":")+w));else for(U in t)Object.prototype.hasOwnProperty.call(t,U)&&(w=n(U,t))&&N.push(e(U)+(g?": ":":")+w);w=0===N.length?"{}":g?"{\n"+g+N.join(",\n"+g)+"\n"+M+"}":"{"+N.join(",")+"}";g=M;return w}}var c=/[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g,v,z={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},I;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(b,e,c){var h;v=g="";if("number"===typeof c)for(h=0;h<c;h+=1)v+=" ";else"string"===typeof c&&(v=c);if((I=e)&&"function"!==typeof e&&("object"!==typeof e||"number"!==typeof e.length))throw Error("JSON2.stringify");return n("",{"":b})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(b,e){function g(b,h){var c,n,t=b[h];if(t&&"object"===typeof t)for(c in t)Object.prototype.hasOwnProperty.call(t,
c)&&(n=g(t,c),void 0!==n?t[c]=n:delete t[c]);return e.call(b,h,t)}var h;b=String(b);c.lastIndex=0;c.test(b)&&(b=b.replace(c,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return h=eval("("+b+")"),"function"===typeof e?g({"":h},""):h;throw new SyntaxError("JSON2.parse");})})();
"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function b(a){return"undefined"!==typeof a}function e(a){return"function"===typeof a}function n(a){return"object"===typeof a}function c(a){return"string"===typeof a||a instanceof String}function h(){var a,d,b;for(a=0;a<arguments.length;a+=1)b=arguments[a],d=b.shift(),c(d)?H[d].apply(H,b):d.apply(H,b)}function g(a,d,b,f){if(a.addEventListener)return a.addEventListener(d,b,f),!0;if(a.attachEvent)return a.attachEvent("on"+d,b);a["on"+d]=b}function v(a,d){var b=
"",f,c;for(f in ka)Object.prototype.hasOwnProperty.call(ka,f)&&(c=ka[f][a],e(c)&&(b+=c(d)));return b}function z(){var a;if(!la)for(la=!0,v("load"),a=0;a<La.length;a++)La[a]();return!0}function I(a,d){var b=q.createElement("script");b.type="text/javascript";b.src=a;b.readyState?b.onreadystatechange=function(){var a=this.readyState;if("loaded"===a||"complete"===a)b.onreadystatechange=null,d()}:b.onload=d;q.getElementsByTagName("head")[0].appendChild(b)}function wa(){var a="";try{a=l.top.document.referrer}catch(d){if(l.parent)try{a=
l.parent.document.referrer}catch(b){a=""}}""===a&&(a=q.referrer);return a}function jb(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function p(a){var d=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return d?d[1]:a}function U(a,d){var b=(new RegExp("[\\?&#]"+d+"=([^&#]*)")).exec(a);return b?kb(b[1]):""}function w(a){var b=function(a,b){return a<<b|a>>>32-b},e=function(a){var b="",d,f;for(d=7;0<=d;d--)f=a>>>4*d&15,b+=f.toString(16);return b},f,c,h=[],g=1732584193,q=4023233417,m=2562383102,l=271733878,
n=3285377520,u,p,r,t,v,w=[];a=lb(x(a));u=a.length;for(f=0;f<u-3;f+=4)c=a.charCodeAt(f)<<24|a.charCodeAt(f+1)<<16|a.charCodeAt(f+2)<<8|a.charCodeAt(f+3),w.push(c);switch(u&3){case 0:f=2147483648;break;case 1:f=a.charCodeAt(u-1)<<24|8388608;break;case 2:f=a.charCodeAt(u-2)<<24|a.charCodeAt(u-1)<<16|32768;break;case 3:f=a.charCodeAt(u-3)<<24|a.charCodeAt(u-2)<<16|a.charCodeAt(u-1)<<8|128}for(w.push(f);14!==(w.length&15);)w.push(0);w.push(u>>>29);w.push(u<<3&4294967295);for(a=0;a<w.length;a+=16){for(f=
0;16>f;f++)h[f]=w[a+f];for(f=16;79>=f;f++)h[f]=b(h[f-3]^h[f-8]^h[f-14]^h[f-16],1);c=g;u=q;p=m;r=l;t=n;for(f=0;19>=f;f++)v=b(c,5)+(u&p|~u&r)+t+h[f]+1518500249&4294967295,t=r,r=p,p=b(u,30),u=c,c=v;for(f=20;39>=f;f++)v=b(c,5)+(u^p^r)+t+h[f]+1859775393&4294967295,t=r,r=p,p=b(u,30),u=c,c=v;for(f=40;59>=f;f++)v=b(c,5)+(u&p|u&r|p&r)+t+h[f]+2400959708&4294967295,t=r,r=p,p=b(u,30),u=c,c=v;for(f=60;79>=f;f++)v=b(c,5)+(u^p^r)+t+h[f]+3395469782&4294967295,t=r,r=p,p=b(u,30),u=c,c=v;g=g+c&4294967295;q=q+u&4294967295;
m=m+p&4294967295;l=l+r&4294967295;n=n+t&4294967295}v=e(g)+e(q)+e(m)+e(l)+e(n);return v.toLowerCase()}function $b(a,b,c){if("translate.googleusercontent.com"===a)""===c&&(c=b),b=U(b,"u"),a=p(b);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))b=q.links[0].href,a=p(b);return[a,b,c]}function M(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));return a}function N(a){a=a&&a.text?a.text:a;if(!c(a)){var d=q.getElementsByTagName("title");
d&&b(d[0])&&(a=d[0].text)}return a}function t(a){return a?!b(a.children)&&b(a.childNodes)||b(a.children)?a.children:[]:[]}function ba(a,d){if(a&&a.indexOf)return a.indexOf(d);if(!b(a)||null===a||!a.length)return-1;var c=a.length;if(0===c)return-1;for(var f=0;f<c;){if(a[f]===d)return f;f++}return-1}function mb(a){function d(a,b){if(l.getComputedStyle)return q.defaultView.getComputedStyle(a,null)[b];if(a.currentStyle)return a.currentStyle[b]}function c(f,e,h,g,m,l,n){var p=f.parentNode,r;a:{for(r=f.parentNode;r;){if(r===
q){r=!0;break a}r=r.parentNode}r=!1}if(!r)return!1;if(9===p.nodeType)return!0;if("0"===d(f,"opacity")||"none"===d(f,"display")||"hidden"===d(f,"visibility"))return!1;b(e)&&b(h)&&b(g)&&b(m)&&b(l)&&b(n)||(e=f.offsetTop,m=f.offsetLeft,g=e+f.offsetHeight,h=m+f.offsetWidth,l=f.offsetWidth,n=f.offsetHeight);if(a===f&&(0===n||0===l)&&"hidden"===d(f,"overflow"))return!1;if(p){if("hidden"===d(p,"overflow")||"scroll"===d(p,"overflow"))if(m+1>p.offsetWidth+p.scrollLeft||m+l-1<p.scrollLeft||e+1>p.offsetHeight+
p.scrollTop||e+n-1<p.scrollTop)return!1;f.offsetParent===p&&(m+=p.offsetLeft,e+=p.offsetTop);return c(p,e,h,g,m,l,n)}return!0}return a?c(a):!1}function Na(a,b){if(b)return b;"piwik.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function ca(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(q.referrer);if(b){if(b[1]!==String(a))return!1;l.name="Piwik_Overlay###"+b[2]+"###"+b[3]}a=l.name.split("###");return 3===a.length&&"Piwik_Overlay"===
a[0]}function bc(a,b,c){var e=l.name.split("###"),h=e[1],g=e[2],m=Na(a,b);I(m+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(m,c,h,g)})}function na(a,d,h){function f(k,a,b,d,c,e){if(!Z){var f;b&&(f=new Date,f.setTime(f.getTime()+b));q.cookie=k+"="+x(a)+(b?";expires="+f.toGMTString():"")+";path="+(d||"/")+(c?";domain="+c:"")+(e?";secure":"")}}function t(k){return Z?0:(k=(new RegExp("(^|;)[ ]*"+k+"=([^;]*)")).exec(q.cookie))?kb(k[2]):0}function z(k){var a;return nb?
(a=/#.*/,k.replace(a,"")):k}function I(k){var a,b,d;for(a=0;a<za.length;a++){b=M(za[a].toLowerCase());if(k===b)return!0;if("."===b.slice(0,1)){if(k===b.slice(1))return!0;d=k.length-b.length;if(0<d&&k.slice(d)===b)return!0}}return!1}function H(k,a){var b=new Image(1,1);b.onload=function(){G=0;"function"===typeof a&&a()};b.src=T+(0>T.indexOf("?")?"?":"&")+k}function ba(k,a,b){var d=new Image(1,1);d.onload=function(){G=0;"function"===typeof b&&b()};d.src=a+(0>T.indexOf("?")?"?":"&")+k}function R(k,a,
oa){b(oa)&&null!==oa||(oa=!0);try{var d=l.XMLHttpRequest?new l.XMLHttpRequest:l.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;d.open("POST",T,!0);d.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!oa?"function"===typeof a&&a():H(k,a)};d.setRequestHeader("Content-Type",ob);d.send(k)}catch(c){oa&&H(k,a)}}function xa(k){k=(new Date).getTime()+k;if(!pa||k>pa)pa=k}function u(k){var a=(new Date).getTime();da&&a<da?(a=da-a,setTimeout(k,a),xa(a+50),da+=50):
(!1===da&&(da=a+800),k())}function K(k,a,b){!Aa&&k&&u(function(){"POST"===pb?R(k,b):H(k,b);xa(a)})}function ya(k,a){var b;b=Aa?!1:k&&k.length;if(b){var d='{"requests":["?'+k.join('","?')+'"]}';u(function(){R(d,null,!1);xa(a)})}}function S(k){return qb+k+"."+Q+"."+rb}function va(){if(Z)return"0";if(!b(F.cookieEnabled)){var k=S("testcookie");f(k,"1");return"1"===t(k)?"1":"0"}return F.cookieEnabled?"1":"0"}function fa(){rb=sb((W||Pa)+(X||"/")).slice(0,4)}function Ma(){var k=S("cvar"),k=t(k);return k.length&&
(k=JSON2.parse(k),n(k))?k:{}}function A(){Qa=(new Date).getTime()}function C(){Ra=!0}function ma(){var k=new Date,a=Math.round(k.getTime()/1E3),b=t(S("id"));b?(k=b.split("."),k.unshift("0")):(Sa||(Sa=sb((F.userAgent||"")+(F.platform||"")+JSON2.stringify(Y)+k.getTime()+Math.random()).slice(0,16)),k=["1",Sa,a,0,a,"",""]);return k}function na(){var k=(new Date).getTime(),a=ma();return 1E3*parseInt(a[2],10)+Ta-k}function Na(k,a,b,d,c,e){var h=na();f(S("id"),k+"."+a+"."+b+"."+d+"."+c+"."+e,h,X,W)}function ga(){var k=
t(S("ref"));if(k.length)try{if(k=JSON2.parse(k),n(k))return k}catch(a){}return["","",0,""]}function tb(){var k=Z;Z=!1;f(S("id"),"",-86400,X,W);f(S("ses"),"",-86400,X,W);f(S("cvar"),"",-86400,X,W);f(S("ref"),"",-86400,X,W);Z=k}function ub(k){if(k&&n(k)){var a=[],b;for(b in k)Object.prototype.hasOwnProperty.call(k,b)&&a.push(b);b={};a.sort();var d=a.length,c;for(c=0;c<d;c++)b[a[c]]=k[a[c]];return b}}function D(k,a,d,c){function h(k,a){var b=JSON2.stringify(k);return 2<b.length?"&"+a+"="+x(b):""}var g,
P=new Date,m=Math.round(P.getTime()/1E3),l,n,r,w,u,B,y,F,A,C,G=O,J=S("ses"),L=S("ref"),N=S("cvar");y=ma();C=t(J);A=ga();var K=qa||Ua,D,H;Z&&tb();if(Aa)return"";l=y[0];n=y[1];w=y[2];r=y[3];u=y[4];B=y[5];b(y[6])||(y[6]="");y=y[6];b(c)||(c="");var M=q.characterSet||q.charset;M&&"utf-8"!==M.toLowerCase()||(M=null);D=A[0];H=A[1];F=A[2];A=A[3];var V;if(C)V=JSON2.parse(C);else{C=Ba/1E3;if(!B||m-B>C)r++,B=u;if(!Va||!D.length){for(g in Ca)if(Object.prototype.hasOwnProperty.call(Ca,g)&&(D=U(K,Ca[g]),D.length))break;
for(g in Da)if(Object.prototype.hasOwnProperty.call(Da,g)&&(H=U(K,Da[g]),H.length))break}u=p(ha);C=A.length?p(A):"";!u.length||I(u)||Va&&C.length&&!I(C)||(A=ha);if(A.length||D.length)F=m,A=[D,H,F,z(A.slice(0,1024))],f(L,JSON2.stringify(A),vb,X,W);k+="&new_session=1"}P.getMonth();u=objPerformance.getParams();L=(new measureLoadPage).get(wb);objPWConfig.set("site_id",Q);objPWConfig.set("tracker_url",T);objPWConfig.set("visitor_id",n);k+="&idsite="+Q+"&rec=1&r="+String(Math.random()).slice(2,8)+"&ltime="+
Math.round(P.getTime()/1E3)+"&url="+x(z(K))+(ha.length?"&urlref="+x(z(ha).substr(0,1E3)):"")+(Ea.length?"&uid="+x(Ea):"")+"&_id="+n+"&_idts="+w+"&_idvc="+r+"&_idn="+l+(D.length?"&_rcn="+x(D):"")+(H.length?"&_rck="+x(H):"")+"&_refts="+F+"&_viewts="+B+(String(y).length?"&_ects="+y:"")+(M?"&cs="+x(M):"")+"&s_img=0&mdata="+xb+"&n_tp="+u.navigation_type+"&t_fl_r="+u.timing_full_response+"&t_dns="+u.timing_dns+"&t_dw="+u.timing_download+"&t_wt="+u.timing_waiting+"&t_rq="+u.timing_request+"&ver="+_version+
"&h_id="+hit_id+"&l_arc="+objScroll.longArticle();if((P=(new Meta).getMeta())&&"object"==typeof P)var R=objTools.serialize(P,"meta");R&&(k+="&"+R);for(g in Y)Object.prototype.hasOwnProperty.call(Y,g)&&(k+="&"+g+"="+Y[g]);a?k+="&data="+x(JSON2.stringify(a)):aa&&(k+="&data="+x(JSON2.stringify(aa)));"sum"in L&&("css"in L.sum&&(k+="&rspf[css][size]="+L.sum.css.size,k+="&rspf[css][count]="+L.sum.css.count,k+="&rspf[css][dur]="+L.sum.css.duration),"script"in L.sum&&(k+="&rspf[script][size]="+L.sum.script.size,
k+="&rspf[script][count]="+L.sum.script.count,k+="&rspf[script][dur]="+L.sum.script.duration),"img"in L.sum&&(k+="&rspf[img][size]="+L.sum.img.size,k+="&rspf[img][count]="+L.sum.img.count,k+="&rspf[img][dur]="+L.sum.img.duration),k+="&rspf[marker]="+yb);a=ub(ea);R=ub(Wa);k+=h(a,"cvar");k+=h(R,"e_cvar");if(O){k+=h(O,"_cvar");for(g in G)Object.prototype.hasOwnProperty.call(G,g)&&(""!==O[g][0]&&""!==O[g][1]||delete O[g]);zb&&f(N,JSON2.stringify(O),Ba,X,W)}Ab&&(Xa?k+="&gt_ms="+Xa:ia&&ia.timing&&ia.timing.requestStart&&
ia.timing.responseEnd&&(k+="&gt_ms="+(ia.timing.responseEnd-ia.timing.requestStart)));g=dc(V);G={depth:g};Na(n,w,r,m,B,b(c)&&String(c).length?c:y);f(J,JSON2.stringify(G),Ba,X,W);k=k+("&depth="+g)+v(d);Ya.length&&(k+="&"+Ya);e(Za)&&(k=Za(k));return k}function dc(k){var a=0;k&&(a=k.depth);k=p(ha);var b=p(location.hostname);return k&&k==b?a+1:a}function Bb(a,E,d,c,e,g){var f="idgoal=0",h,P=new Date,m=[],l;String(a).length&&(f+="&ec_id="+x(a),h=Math.round(P.getTime()/1E3));f+="&revenue="+E;String(d).length&&
(f+="&ec_st="+d);String(c).length&&(f+="&ec_tx="+c);String(e).length&&(f+="&ec_sh="+e);String(g).length&&(f+="&ec_dt="+g);if(y){for(l in y)Object.prototype.hasOwnProperty.call(y,l)&&(b(y[l][1])||(y[l][1]=""),b(y[l][2])||(y[l][2]=""),b(y[l][3])&&0!==String(y[l][3]).length||(y[l][3]=0),b(y[l][4])&&0!==String(y[l][4]).length||(y[l][4]=1),m.push(y[l]));f+="&ec_items="+x(JSON2.stringify(m))}f=D(f,aa,"ecommerce",h);K(f,B)}function ec(a,b){var d=new Date,c=a||Cb,c=c.substr(0,500),c=D("action_name="+x(N(c)),
b,"log");K(c,B);$a&&ra&&!Db&&(Db=!0,g(q,"click",A),g(q,"mouseup",A),g(q,"mousedown",A),g(q,"mousemove",A),g(q,"mousewheel",A),g(l,"DOMMouseScroll",A),g(l,"scroll",A),g(q,"keypress",A),g(q,"keydown",A),g(q,"keyup",A),g(l,"resize",A),g(l,"focus",A),g(l,"blur",A),Qa=d.getTime(),setTimeout(function cc(){var a;d=new Date;Qa+ra>d.getTime()&&($a<d.getTime()&&(a=D("ping=1",b,"ping"),K(a,B)),setTimeout(cc,ra))},ra))}function ab(a,b){var d,c="(^| )(piwik[_-]"+b;if(a)for(d=0;d<a.length;d++)c+="|"+a[d];return new RegExp(c+
")( |$)")}function sa(a){return T&&a&&0===String(a).indexOf(T)}function bb(a){var E=a;for(a=E.parentNode;null!==a&&b(a)&&!m.isLinkElement(E);)E=a,a=E.parentNode;a=E;if(m.hasNodeAttribute(a,"href")&&b(a.href)&&(E=m.getAttributeValueFromNode(a,"href"),!sa(E))){var E=a.hostname||p(a.href),d=E.toLowerCase(),E=a.href.replace(E,d);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(E)){a=a.className;d=I(d);if(sa(E))a=0;else{var c=ab(Eb,"download"),f=ab(Fb,"link"),e=new RegExp("\\.("+
ta+")([?&#]|$)","i");a=f.test(a)?"link":c.test(a)||e.test(E)?"download":d?0:"link"}if(a)return{type:a,href:E}}}}function ua(a,b,d,c){if(a=r.buildInteractionRequestParams(a,b,d,c))return D(a,null,"contentInteraction")}function Gb(a,E,d,c,f){if(b(a)){if(sa(a))return a;var e=r.toAbsoluteUrl(a),e="redirecturl="+x(e)+"&",e=e+ua(E,d,c,f||a);a="&";0>T.indexOf("?")&&(a="?");return T+a+e}}function cb(a,b){if(!a||!b)return!1;var d=r.findTargetNode(a);if(r.shouldIgnoreInteraction(d))return!1;var d=r.findTargetNodeNoDefault(a),
c;if(c=d)c=!(d&&b&&(d.contains?d.contains(b):d===b||d.compareDocumentPosition&&d.compareDocumentPosition(b)&16));return c?!1:!0}function Hb(a,b,d){if(a){var c=r.findParentContentNode(a);if(c&&cb(c,a)&&(a=r.buildContentBlock(c)))return!a.target&&d&&(a.target=d),r.buildInteractionRequestParams(b,a.name,a.piece,a.target)}}function Ib(a){if(!V||!V.length)return!1;var b,d;for(b=0;b<V.length;b++)if((d=V[b])&&d.name===a.name&&d.piece===a.piece&&d.target===a.target)return!0;return!1}function db(a){if(!a)return!1;
var b=r.findTargetNode(a);if(!b||r.shouldIgnoreInteraction(b))return!1;var d=bb(b);if(eb&&d&&d.type)return!1;if(m.isLinkElement(b)&&m.hasNodeAttributeWithValue(b,"href")){d=String(m.getAttributeValueFromNode(b,"href"));if(0===d.indexOf("#"))return!1;if(sa(d))return!0;if(!r.isUrlToCurrentDomain(d))return!1;var c=r.buildContentBlock(a);if(!c)return;a=c.name;var f=c.piece,c=c.target;if(!m.hasNodeAttributeWithValue(b,r.CONTENT_TARGET_ATTR)||b.wasContentTargetAttrReplaced)b.wasContentTargetAttrReplaced=
!0,c=r.toAbsoluteUrl(d),m.setAnyAttribute(b,r.CONTENT_TARGET_ATTR,c);d=Gb(d,"click",a,f,c);r.setHrefAttribute(b,d);return!0}return!1}function Jb(a){return function(b){if(a){var d=r.findParentContentNode(a),c;b&&(c=b.target||b.srcElement);c||(c=a);if(cb(d,c)){xa(B);m.isLinkElement(a)&&m.hasNodeAttributeWithValue(a,"href")&&m.hasNodeAttributeWithValue(a,r.CONTENT_TARGET_ATTR)&&(b=m.getAttributeValueFromNode(a,"href"),!sa(b)&&a.wasContentTargetAttrReplaced&&m.setAnyAttribute(a,r.CONTENT_TARGET_ATTR,
""));b=bb(a);if(Fa&&b&&b.type)return b.type;if(db(d))return"href";if(d=r.buildContentBlock(d))return d=ua("click",d.name,d.piece,d.target),K(d,B),d}}}}function Kb(a){if(a&&a.length){var b,d;for(b=0;b<a.length;b++)(d=r.findTargetNode(a[b]))&&!d.contentInteractionTrackingSetupDone&&(d.contentInteractionTrackingSetupDone=!0,g(d,"click",Jb(d)))}}function Lb(a,b){if(!a||!a.length)return[];var d,c;for(d=0;d<a.length;d++)Ib(a[d])?(a.splice(d,1),d--):V.push(a[d]);if(!a||!a.length)return[];if(b&&b.length)for(d=
0;d<b.length;d++)db(b[d]);Kb(b);var f=[];for(d=0;d<a.length;d++)c=D(r.buildImpressionRequestParams(a[d].name,a[d].piece,a[d].target),void 0,"contentImpressions"),f.push(c);return f}function Ga(a){var b=r.collectContent(a);return Lb(b,a)}function fb(a){if(!a||!a.length)return[];var b;for(b=0;b<a.length;b++)r.isNodeVisible(a[b])||(a.splice(b,1),b--);return a&&a.length?Ga(a):[]}function Mb(a,b,d){a=r.buildImpressionRequestParams(a,b,d);return D(a,null,"contentImpression")}function Nb(a,b){if(a){var d=
r.findParentContentNode(a);if(d=r.buildContentBlock(d))return b||(b="Unknown"),ua(b,d.name,d.piece,d.target)}}function Ob(a,d,c,f,e){if(0===String(a).length||0===String(d).length)return!1;a="e_c="+x(a)+"&e_a="+x(d)+(b(c)?"&e_n="+x(c):"")+(b(f)?"&e_v="+x(f):"");e=D(a,e,"event");K(e,B)}function Pb(a,b,d,c,f){b=b+"="+x(z(a));(a=Hb(f,"click",a))&&(b+="&"+a);d=D(b,d,"link");K(d,c?0:B,c)}function Qb(a,b){return""!==a?a+b.charAt(0).toUpperCase()+b.slice(1):b}function J(a){var b,d,c=["","webkit","ms","moz"],
f;if(!Rb)for(d=0;d<c.length;d++)if(f=c[d],Object.prototype.hasOwnProperty.call(q,Qb(f,"hidden"))){"prerender"===q[Qb(f,"visibilityState")]&&(b=!0);break}b?g(q,f+"visibilitychange",function Oa(){q.removeEventListener(f+"visibilitychange",Oa,!1);a()}):a()}function Ha(a){"complete"===q.readyState?a():l.addEventListener?l.addEventListener("load",a):l.attachEvent&&l.attachEvent("onLoad",a)}function gb(a){var b=!1;(b=q.attachEvent?"complete"===q.readyState:"loading"!==q.readyState)?a():q.addEventListener?
q.addEventListener("DOMContentLoaded",a):q.attachEvent&&q.attachEvent("onreadystatechange",a)}function Sb(a){var b=bb(a);b&&b.type&&(b.href=lb(b.href),Pb(b.href,b.type,void 0,null,a))}function hb(a){var b,d;a=a||l.event;b=a.which||a.button;d=a.target||a.srcElement;"click"===a.type?d&&Sb(d):"mousedown"===a.type?1!==b&&2!==b||!d?Ia=Ja=null:(Ia=b,Ja=d):"mouseup"===a.type&&(b===Ia&&d===Ja&&Sb(d),Ia=Ja=null)}function Tb(a,b){b?(g(a,"mouseup",hb,!1),g(a,"mousedown",hb,!1)):g(a,"click",hb,!1)}function Ub(a){if(!Fa){Fa=
!0;var b,d=ab(Vb,"ignore"),c=q.links;if(c)for(b=0;b<c.length;b++)d.test(c[b].className)||Tb(c[b],a)}}function Wb(a,b,d){function c(){f=!0}if(ja)return!0;ja=!0;var f=!1,e,g;Ha(function(){function h(a){setTimeout(function(){ja&&(f=!1,d.trackVisibleContentImpressions(),h(a))},a)}function P(a){setTimeout(function(){ja&&(f&&(f=!1,d.trackVisibleContentImpressions()),P(a))},a)}if(a){e=["scroll","resize"];for(g=0;g<e.length;g++)q.addEventListener?q.addEventListener(e[g],c):l.attachEvent("on"+e[g],c);P(100)}b&&
0<b&&(b=parseInt(b,10),h(b))})}var Ka={},ib=$b(q.domain,l.location.href,wa()),Pa=M(ib[0]),Ua=ib[1],ha=ib[2],Xb=!1,pb="GET",ob="application/x-www-form-urlencoded; charset=UTF-8",T=a||"//a.ria.ru/counter",Yb="",Ya="",Q=d||"",xb="",yb="",wb=null,Ea="",qa,Cb=q.title,ta="7z|aac|apk|ar[cj]|as[fx]|avi|azw3|bin|csv|deb|dmg|docx?|epub|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mobi|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",
za=[Pa],Vb=[],Eb=[],Fb=[],B=500,$a,ra,nb,aa,Ca=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],Da=["pk_kwd","piwik_kwd","utm_term"],qb="_pk_",W,X,Z=!1,Aa,Rb,Va,Ta=339552E5,Ba=18E5,vb=15768E6,Ab=!0,Xa=0,zb=!1,O=!1,Za,ea={},Wa={},y={},Y={},V=[],ja=!1,da=!1,Fa=!1,eb=!1,Db=!1,Qa,Ra=!1,Ia,Ja,sb=w,rb,Sa=h;(function(){var a,d,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",
java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},f=/Mac OS X.*Safari\//.test(F.userAgent)?l.devicePixelRatio||1:1;if(!/MSIE/.test(F.userAgent)){if(F.mimeTypes&&F.mimeTypes.length)for(a in c)Object.prototype.hasOwnProperty.call(c,a)&&(d=F.mimeTypes[c[a]],Y[a]=d&&d.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&b(F.javaEnabled)&&F.javaEnabled()&&(Y.java="1");e(l.GearsFactory)&&(Y.gears="1");Y.cookie=va()}Y.res=Zb.width*f+"x"+Zb.height*
f})();fa();v("run",function(a,d){var f=null;if(c(a)&&!b(Ka[a])&&d){if(n(d))f=d;else if(c(d))try{eval("hookObj ="+d)}catch(e){}Ka[a]=f}return f});return{hook:Ka,getHook:function(a){return Ka[a]},getQuery:function(){return m},getContent:function(){return r},buildContentImpressionRequest:Mb,buildContentInteractionRequest:ua,buildContentInteractionRequestNode:Nb,buildContentInteractionTrackingRedirectUrl:Gb,getContentImpressionsRequestsFromNodes:Ga,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:fb,
trackCallbackOnLoad:Ha,trackCallbackOnReady:gb,buildContentImpressionsRequests:Lb,wasContentImpressionAlreadyTracked:Ib,appendContentInteractionToRequestIfPossible:Hb,setupInteractionsTracking:Kb,trackContentImpressionClickInteraction:Jb,internalIsNodeVisible:mb,isNodeAuthorizedToTriggerInteraction:cb,replaceHrefIfInternalLink:db,getConfigDownloadExtensions:function(){return ta},enableTrackOnlyVisibleContent:function(a,b){return Wb(a,b,this)},clearTrackedContentImpressions:function(){V=[]},getTrackedContentImpressions:function(){return V},
getTrackerUrl:function(){return T},clearEnableTrackOnlyVisibleContent:function(){ja=!1},disableLinkTracking:function(){eb=Fa=!1},getConfigVisitorCookieTimeout:function(){return Ta},getRemainingVisitorCookieTimeout:na,getVisitorId:function(){return ma()[1]},getVisitorInfo:function(){return ma()},getAttributionInfo:function(){return ga()},getAttributionCampaignName:function(){return ga()[0]},getAttributionCampaignKeyword:function(){return ga()[1]},getAttributionReferrerTimestamp:function(){return ga()[2]},
getAttributionReferrerUrl:function(){return ga()[3]},setTrackerUrl:function(a){T=a},setSiteId:function(a){Q=a},setMetadata:function(a){xb=a},setResperfMarker:function(a){yb=a},setCDNMask:function(a){wb=a},setUserId:function(a){Ea=a},getUserId:function(){return Ea},setCustomData:function(a,b){n(a)?aa=a:(aa||(aa={}),aa[a]=b)},getCustomData:function(){return aa},setCustomRequestProcessing:function(a){Za=a},appendToTrackingUrl:function(a){Ya=a},getRequest:function(a){return D(a)},addPlugin:function(a,
b){ka[a]=b},setCustomVariable:function(a,d,f,e){b(e)||(e="visit");b(d)&&(b(f)||(f=""),0<a&&(d=c(d)?d:String(d),f=c(f)?f:String(f),d=[d.slice(0,200),f.slice(0,200)],"visit"===e||2===e?(!1===O&&(O=Ma()),O[a]=d):"page"===e||3===e?ea[a]=d:"event"===e&&(Wa[a]=d)))},getCustomVariable:function(a,d){var c;b(d)||(d="visit");if("page"===d||3===d)c=ea[a];else if("event"===d)c=Wa[a];else if("visit"===d||2===d)!1===O&&(O=Ma()),c=O[a];return!b(c)||c&&""===c[0]?!1:c},deleteCustomVariable:function(a,b){this.getCustomVariable(a,
b)&&this.setCustomVariable(a,"","",b)},storeCustomVariablesInCookie:function(){zb=!0},setLinkTrackingTimer:function(a){B=a},setDownloadExtensions:function(a){ta=a},addDownloadExtensions:function(a){ta+="|"+a},setDomains:function(a){za=c(a)?[a]:a;za.push(Pa)},setIgnoreClasses:function(a){Vb=c(a)?[a]:a},setRequestMethod:function(a){pb=a||"GET"},setRequestContentType:function(a){ob=a||"application/x-www-form-urlencoded; charset=UTF-8"},setReferrerUrl:function(a){ha=a},setCustomUrl:function(a){var b=
Ua,d;jb(a)?qa=a:"/"===a.slice(0,1)?qa=jb(b)+"://"+p(b)+a:(b=z(b),d=b.indexOf("?"),0<=d&&(b=b.slice(0,d)),d=b.lastIndexOf("/"),d!==b.length-1&&(b=b.slice(0,d+1)),qa=b+a)},setDocumentTitle:function(a){Cb=a},setAPIUrl:function(a){Yb=a},setDownloadClasses:function(a){Eb=c(a)?[a]:a},setLinkClasses:function(a){Fb=c(a)?[a]:a},setCampaignNameKey:function(a){Ca=c(a)?[a]:a},setCampaignKeywordKey:function(a){Da=c(a)?[a]:a},discardHashTag:function(a){nb=a},setCookieNamePrefix:function(a){qb=a;O=Ma()},setCookieDomain:function(a){W=
M(a);fa()},setCookiePath:function(a){X=a;fa()},setVisitorCookieTimeout:function(a){Ta=1E3*a},setSessionCookieTimeout:function(a){Ba=1E3*a},setReferralCookieTimeout:function(a){vb=1E3*a},setConversionAttributionFirstReferrer:function(a){Va=a},disableCookies:function(){Z=!0;Y.cookie="0"},deleteCookies:function(){tb()},setDoNotTrack:function(a){var b=F.doNotTrack||F.msDoNotTrack;(Aa=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){Tb(a,b)},enableLinkTracking:function(a){eb=
!0;la?Ub(a):La.push(function(){Ub(a)})},enableJSErrorTracking:function(){if(!Xb){Xb=!0;var a=l.onerror;l.onerror=function(b,d,c,f,e){J(function(){var a=d+":"+c;f&&(a+=":"+f);Ob("JavaScript Errors",a,b)});return a?a(b,d,c,f,e):!1}}},disablePerformanceTracking:function(){Ab=!1},setGenerationTimeMs:function(a){Xa=parseInt(a,10)},setHeartBeatTimer:function(a,b){$a=(new Date).getTime()+1E3*a;ra=1E3*b},killFrame:function(){l.location!==l.top.location&&(l.top.location=l.location)},redirectFile:function(a){"file:"===
l.location.protocol&&(l.location=a)},setCountPreRendered:function(a){Rb=a},trackGoal:function(a,b,d){J(function(){var c=D("idgoal="+a+(b?"&revenue="+b:""),d,"goal");K(c,B)})},trackLink:function(a,b,d,c){J(function(){Pb(a,b,d,c)})},trackPageView:function(a,b){V=[];ca(Q)?J(function(){bc(T,Yb,Q)}):J(function(){ec(a,b)})},trackAllContentImpressions:function(){ca(Q)||J(function(){gb(function(){var a=r.findContentNodes(),a=Ga(a);ya(a,B)})})},trackVisibleContentImpressions:function(a,d){ca(Q)||(b(a)||(a=
!0),b(d)||(d=750),Wb(a,d,this),J(function(){Ha(function(){var a=r.findContentNodes(),a=fb(a);ya(a,B)})}))},trackContentImpression:function(a,b,d){!ca(Q)&&a&&(b=b||"Unknown",J(function(){var c=Mb(a,b,d);K(c,B)}))},trackContentImpressionsWithinNode:function(a){!ca(Q)&&a&&J(function(){ja?Ha(function(){var b=r.findContentNodesWithinNode(a),b=fb(b);ya(b,B)}):gb(function(){var b=r.findContentNodesWithinNode(a),b=Ga(b);ya(b,B)})})},trackContentInteraction:function(a,b,d,c){!ca(Q)&&a&&b&&(d=d||"Unknown",
J(function(){var f=ua(a,b,d,c);K(f,B)}))},trackContentInteractionNode:function(a,b){!ca(Q)&&a&&J(function(){var d=Nb(a,b);K(d,B)})},trackEvent:function(a,b,d,c){J(function(){Ob(a,b,d,c)})},trackSiteSearch:function(a,d,c){J(function(){var f=D("search="+x(a)+(d?"&search_cat="+x(d):"")+(b(c)?"&search_count="+c:""),void 0,"sitesearch");K(f,B)})},setEcommerceView:function(a,d,c,f){b(c)&&c.length?c instanceof Array&&(c=JSON2.stringify(c)):c="";ea[5]=["_pkc",c];b(f)&&String(f).length&&(ea[2]=["_pkp",f]);
if(b(a)&&a.length||b(d)&&d.length)b(a)&&a.length&&(ea[3]=["_pks",a]),b(d)&&d.length||(d=""),ea[4]=["_pkn",d]},addEcommerceItem:function(a,b,d,c,f){a.length&&(y[a]=[a,b,d,c,f])},trackEcommerceOrder:function(a,d,c,f,e,g){String(a).length&&b(d)&&Bb(a,d,c,f,e,g)},trackEcommerceCartUpdate:function(a){b(a)&&Bb("",a,"","","","")},startPing:function(a,b){function d(){if(!0===Ra){Ra=!1;var a=objEvents.getReguest();0<a.events.length&&(a=objTools.serialize(a),ba(a,b))}}a=0>=a?5E3:a;b=b||"//a.ria.ru/ping";var c=
!1,f=ma();g(q,"click",C);g(q,"mouseup",C);g(q,"mousedown",C);g(q,"mousemove",C);g(q,"mousewheel",C);g(l,"DOMMouseScroll",C);g(l,"scroll",C);g(q,"keypress",C);g(q,"keydown",C);g(q,"keyup",C);g(l,"resize",C);g(l,"focus",C);g(l,"blur",C);g(l,"scroll",function(){!1===c&&(c=!0,setTimeout(d,2E3,!0))});objEvents.setRequestVar("idsite",Q);objEvents.setRequestVar("url",x(z(qa||Ua)));objEvents.setRequestVar("_id",f[1]);objEvents.setRequestVar("_idts",f[2]);setTimeout(function Oa(){d();pingTimerID=setTimeout(Oa,
a)},a)}}}var pa,ka={},q=document,F=navigator,Zb=screen,l=window,ia=l.performance||l.mozPerformance||l.msPerformance||l.webkitPerformance,la=!1,La=[],x=l.encodeURIComponent,kb=l.decodeURIComponent,lb=unescape,H,G,va,m={htmlCollectionToArray:function(a){var b=[],c;if(!a||!a.length)return b;for(c=0;c<a.length;c++)b.push(a[c]);return b},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return this.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];
var b,c,f=[];for(b=0;b<a.length;b++)c=this.find(a[b]),f=f.concat(c);return f=this.makeNodesUnique(f)},findNodesByTagName:function(a,b){if(!a||!b||!a.getElementsByTagName)return[];var c=a.getElementsByTagName(b);return this.htmlCollectionToArray(c)},makeNodesUnique:function(a){var b=[].concat(a);a.sort(function(a,c){if(a===c)return 0;var f=ba(b,a),e=ba(b,c);return f===e?0:f>e?-1:1});if(1>=a.length)return a;var c=0,f=0,e=[],g;for(g=a[c++];g;)g===a[c]&&(f=e.push(c)),g=a[c++]||null;for(;f--;)a.splice(e[f],
1);return a},getAttributeValueFromNode:function(a,b){if(this.hasNodeAttribute(a,b)){if(a&&a.getAttribute)return a.getAttribute(b);if(a&&a.attributes&&"undefined"!==typeof a.attributes[b]){if(a.attributes[b].value)return a.attributes[b].value;if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var c,f=a.attributes;if(f){for(c=0;c<f.length;c++)if(f[c].nodeName===b)return f[c].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,b){return!!this.getAttributeValueFromNode(a,b)},hasNodeAttribute:function(a,
b){return a&&a.hasAttribute?a.hasAttribute(b):a&&a.attributes?"undefined"!==typeof a.attributes[b]:!1},hasNodeCssClass:function(a,b){if(a&&b&&a.className){var c=a.className.split(" ");if(-1!==ba(c,b))return!0}return!1},findNodesHavingAttribute:function(a,b,c){c||(c=[]);if(!a||!b)return c;a=t(a);if(!a||!a.length)return c;var f,e;for(f=0;f<a.length;f++)e=a[f],this.hasNodeAttribute(e,b)&&c.push(e),c=this.findNodesHavingAttribute(e,b,c);return c},findFirstNodeHavingAttribute:function(a,b){if(a&&b){if(this.hasNodeAttribute(a,
b))return a;var c=this.findNodesHavingAttribute(a,b);if(c&&c.length)return c[0]}},findFirstNodeHavingAttributeWithValue:function(a,b){if(a&&b){if(this.hasNodeAttributeWithValue(a,b))return a;var c=this.findNodesHavingAttribute(a,b);if(c&&c.length){var f;for(f=0;f<c.length;f++)if(this.getAttributeValueFromNode(c[f],b))return c[f]}}},findNodesHavingCssClass:function(a,b,c){c||(c=[]);if(!a||!b)return c;if(a.getElementsByClassName)return b=a.getElementsByClassName(b),this.htmlCollectionToArray(b);a=t(a);
if(!a||!a.length)return[];var f,e;for(f=0;f<a.length;f++)e=a[f],this.hasNodeCssClass(e,b)&&c.push(e),c=this.findNodesHavingCssClass(e,b,c);return c},findFirstNodeHavingClass:function(a,b){if(a&&b){if(this.hasNodeCssClass(a,b))return a;var c=this.findNodesHavingCssClass(a,b);if(c&&c.length)return c[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==ba(["a","area"],a)},setAnyAttribute:function(a,b,c){a&&b&&(a.setAttribute?a.setAttribute(b,c):a[b]=c)}},r={CONTENT_ATTR:"data-track-content",
CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return m.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];
var b=m.findNodesHavingCssClass(a,this.CONTENT_CLASS),c=m.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(c&&c.length){var f;for(f=0;f<c.length;f++)b.push(c[f])}m.hasNodeAttribute(a,this.CONTENT_ATTR)?b.push(a):m.hasNodeCssClass(a,this.CONTENT_CLASS)&&b.push(a);return b=m.makeNodesUnique(b)},findParentContentNode:function(a){if(a)for(var b=0;a&&a!==q&&a.parentNode;){if(m.hasNodeAttribute(a,this.CONTENT_ATTR)||m.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<b)break;b++}},findPieceNode:function(a){var b;
(b=m.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(b=m.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return b?b:a},findTargetNodeNoDefault:function(a){if(a){var b=m.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(b||(b=m.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(b=m.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return b}},findTargetNode:function(a){var b=this.findTargetNodeNoDefault(a);return b?b:a},findContentName:function(a){if(a){var b=
m.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(b)return m.getAttributeValueFromNode(b,this.CONTENT_NAME_ATTR);if(b=this.findContentPiece(a))return this.removeDomainIfIsInLink(b);if(m.hasNodeAttributeWithValue(a,"title"))return m.getAttributeValueFromNode(a,"title");b=this.findPieceNode(a);if(m.hasNodeAttributeWithValue(b,"title"))return m.getAttributeValueFromNode(b,"title");a=this.findTargetNode(a);if(m.hasNodeAttributeWithValue(a,"title"))return m.getAttributeValueFromNode(a,
"title")}},findContentPiece:function(a){if(a){var b=m.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(b)return m.getAttributeValueFromNode(b,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var b=this.findTargetNode(a);if(m.hasNodeAttributeWithValue(b,this.CONTENT_TARGET_ATTR))return m.getAttributeValueFromNode(b,this.CONTENT_TARGET_ATTR);if(m.hasNodeAttributeWithValue(b,"href"))return a=
m.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(m.hasNodeAttributeWithValue(a,"href"))return a=m.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||
(a="/"));return a},findMediaUrlInNode:function(a){if(a){var b=a.nodeName.toLowerCase();if(-1!==ba(["img","embed","video","audio"],b)&&m.findFirstNodeHavingAttributeWithValue(a,"src"))return a=m.findFirstNodeHavingAttributeWithValue(a,"src"),m.getAttributeValueFromNode(a,"src");if("object"===b&&m.hasNodeAttributeWithValue(a,"data"))return m.getAttributeValueFromNode(a,"data");if("object"===b){if((b=m.findNodesByTagName(a,"param"))&&b.length){var c;for(c=0;c<b.length;c++)if("movie"===m.getAttributeValueFromNode(b[c],
"name")&&m.hasNodeAttributeWithValue(b[c],"value"))return m.getAttributeValueFromNode(b[c],"value")}if((a=m.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,""):a},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var b=a.getBoundingClientRect(),c=q.documentElement||{},f=0>b.top;f&&a.offsetTop&&(f=0<a.offsetTop+b.height);a=c.clientWidth;l.innerWidth&&a>l.innerWidth&&
(a=l.innerWidth);c=c.clientHeight;l.innerHeight&&c>l.innerHeight&&(c=l.innerHeight);return(0<b.bottom||f)&&0<b.right&&b.left<a&&(b.top<c||f)},isNodeVisible:function(a){var b=mb(a);a=this.isOrWasNodeInViewport(a);return b&&a},buildInteractionRequestParams:function(a,b,c,f){var e="";a&&(e+="c_i="+x(a));b&&(e&&(e+="&"),e+="c_n="+x(b));c&&(e&&(e+="&"),e+="c_p="+x(c));f&&(e&&(e+="&"),e+="c_t="+x(f));return e},buildImpressionRequestParams:function(a,b,c){a="c_n="+x(a)+"&c_p="+x(b);c&&(a+="&c_t="+x(c));
return a},buildContentBlock:function(a){if(a){var b=this.findContentName(a),c=this.findContentPiece(a);a=this.findContentTarget(a);b=this.trim(b);c=this.trim(c);a=this.trim(a);return{name:b||"Unknown",piece:c||"Unknown",target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var c=[],e,f;for(e=0;e<a.length;e++)f=this.buildContentBlock(a[e]),b(f)&&c.push(f);return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||l.location;a.origin||(a.origin=a.protocol+
"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=
this.toAbsoluteUrl(a);if(!a)return!1;var b=this.getLocation().origin;return b===a?!0:0===String(a).indexOf(b)?":"===String(a).substr(b.length,1)?!1:!0:!1},setHrefAttribute:function(a,b){a&&b&&m.setAnyAttribute(a,"href",b)},shouldIgnoreInteraction:function(a){var b=m.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=m.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return b||a}};g(l,"beforeunload",function(){var a;v("unload");if(pa){do a=new Date;while(a.getTimeAlias()<pa)}},!1);(function(){var a;
q.addEventListener?g(q,"DOMContentLoaded",function P(){q.removeEventListener("DOMContentLoaded",P,!1);z()}):q.attachEvent&&(q.attachEvent("onreadystatechange",function f(){"complete"===q.readyState&&(q.detachEvent("onreadystatechange",f),z())}),q.documentElement.doScroll&&l===l.top&&function ac(){if(!la){try{q.documentElement.doScroll("left")}catch(a){setTimeout(ac,0);return}z()}}());/WebKit/.test(F.userAgent)&&(a=setInterval(function(){if(la||/loaded|complete/.test(q.readyState))clearInterval(a),
z()},10));g(l,"load",z,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;H=new na;var fa={setTrackerUrl:1,setAPIUrl:1,setSiteId:1,disableCookies:1,enableLinkTracking:1,setMetadata:1,setResperfMarker:1,setCDNMask:1},R;for(G=0;G<_paq.length;G++)R=_paq[G][0],fa[R]&&(h(_paq[G]),delete _paq[G],1<fa[R]&&void 0!==console&&console&&console.error&&console.error("The method "+R+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/api-reference/tracking-javascript#multiple-piwik-trackers'),
fa[R]++);for(G=0;G<_paq.length;G++)_paq[G]&&h(_paq[G]);_paq=new function(){return{push:h}};va={addPlugin:function(a,b){ka[a]=b},getTracker:function(a,b){return new na(a,b,H.getVisitorId())},getAsyncTracker:function(){return H}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return va});return va}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=Piwik)})();
if("function"!==typeof piwik_log)var piwik_log=function(b,e,n,c){function h(b){try{return eval("piwik_"+b)}catch(c){}}var g=Piwik.getTracker(n,e);g.setDocumentTitle(b);g.setCustomData(c);(b=h("tracker_pause"))&&g.setLinkTrackingTimer(b);(b=h("download_extensions"))&&g.setDownloadExtensions(b);(b=h("hosts_alias"))&&g.setDomains(b);(b=h("ignore_classes"))&&g.setIgnoreClasses(b);g.trackPageView();h("install_tracker")&&(piwik_track=function(b,c,e,h){g.setSiteId(c);g.setTrackerUrl(e);g.trackLink(b,h)},
g.enableLinkTracking())};var _paq=_paq||[];_paq.push(["startPing",500]);
