/*
 jQuery Smart Banner
 Copyright (c) 2012 Arnold Daniels <arnold@jasny.net>
 Based on 'jQuery Smart Web App Banner' by Kurt Zenisek @ kzeni.com
*/
!function(a){var g=function(b){this.origHtmlMargin=parseFloat(a("html").css("margin-top"));this.options=a.extend({},a.smartbanner.defaults,b);b=navigator.standalone;var c=navigator.userAgent;this.options.force?this.type=this.options.force:null!=c.match(/iPad|iPhone|iPod/i)?null!=c.match(/Safari/i)&&(null!=c.match(/CriOS/i)||6>window.Number(navigator.userAgent.substr(navigator.userAgent.indexOf("OS ")+3,3).replace("_",".")))&&(this.type="ios"):null!=c.match(/Android/i)?this.type="android":null!=c.match(/Windows NT 6.2/i)&&
null!==c.match(/Touch/i)&&(this.type="windows");!this.type||b||this.getCookie("sb-closed")||this.getCookie("sb-installed")||(this.scale="auto"==this.options.scale?a(window).width()/window.screen.width:this.options.scale,1>this.scale&&(this.scale=1),b=a("android"==this.type?'meta[name="google-play-app"]':"ios"==this.type?'meta[name="apple-itunes-app"]':'meta[name="msApplication-ID"]'),0!=b.length&&("windows"==this.type?(this.pfn=a('meta[name="msApplication-PackageFamilyName"]').attr("content"),this.appId=
b.attr("content")[1]):this.appId=/app-id=([^\s,]+)/.exec(b.attr("content"))[1],this.title=this.options.title?this.options.title:a("title").text().replace(/\s*[|\-\u00b7].*$/,""),this.author=this.options.author?this.options.author:a('meta[name="author"]').length?a('meta[name="author"]').attr("content"):window.location.hostname,this.create(),this.show(),this.listen()))};g.prototype={constructor:g,create:function(){var b,c=this.options.url?this.options.url:("windows"==this.type?"ms-windows-store:PDP?PFN="+
this.pfn:"android"==this.type?"market://details?id=":"https://itunes.apple.com/"+this.options.appStoreLanguage+"/app/id")+this.appId,d=this.options.price?this.options.price+(""!=this.options.inGooglePlay||""!=this.options.inAppStore?" - "+("android"==this.type?this.options.inGooglePlay:"ios"==this.type?this.options.inAppStore:this.options.inWindowsStore):""):"",e=null===this.options.iconGloss?"ios"==this.type:this.options.iconGloss;a("body").append('<div id="smartbanner" class="'+this.type+'"><div class="sb-container"><a href="#" class="sb-close">&times;</a><span class="sb-icon"></span><div class="sb-info"><strong>'+
this.title+"</strong><span>"+this.author+"</span><span>"+d+'</span></div><a href="'+c+'" class="sb-button"><span>'+this.options.button+"</span></a></div></div>");this.options.icon?b=this.options.icon:0<a('link[rel="apple-touch-icon-precomposed"]').length?(b=a('link[rel="apple-touch-icon-precomposed"]').attr("href"),null===this.options.iconGloss&&(e=!1)):0<a('link[rel="apple-touch-icon"]').length?b=a('link[rel="apple-touch-icon"]').attr("href"):0<a('meta[name="msApplication-TileImage"]').length?b=
a('meta[name="msApplication-TileImage"]').attr("content"):0<a('meta[name="msapplication-TileImage"]').length&&(b=a('meta[name="msapplication-TileImage"]').attr("content"));b?(a("#smartbanner .sb-icon").css("background-image","url("+b+")"),e&&a("#smartbanner .sb-icon").addClass("gloss")):a("#smartbanner").addClass("no-icon");this.bannerHeight=a("#smartbanner").outerHeight()+2;1<this.scale&&(a("#smartbanner").css("top",parseFloat(a("#smartbanner").css("top"))*this.scale).css("height",parseFloat(a("#smartbanner").css("height"))*
this.scale),a("#smartbanner .sb-container").css("-webkit-transform","scale("+this.scale+")").css("-msie-transform","scale("+this.scale+")").css("-moz-transform","scale("+this.scale+")").css("width",a(window).width()/this.scale))},listen:function(){a("#smartbanner .sb-close").on("click",a.proxy(this.close,this));a("#smartbanner .sb-button").on("click",a.proxy(this.install,this))},show:function(b){a("#smartbanner").stop().css({top:a("html").origHtmlMargin+this.bannerHeight*this.scale},this.options.speedIn).addClass("shown");
a("html").animate({marginTop:this.origHtmlMargin+this.bannerHeight*this.scale},this.options.speedIn,"swing",b)},hide:function(b){a("#smartbanner").stop().animate({top:-1*this.bannerHeight*this.scale},this.options.speedOut).removeClass("shown");a("html").animate({marginTop:this.origHtmlMargin},this.options.speedOut,"swing",b)},close:function(a){a.preventDefault();this.hide();this.setCookie("sb-closed","true",this.options.daysHidden)},install:function(a){this.hide();this.setCookie("sb-installed","true",
this.options.daysReminder)},setCookie:function(a,c,d){var b=new Date;b.setDate(b.getDate()+d);c=escape(c)+(null==d?"":"; expires="+b.toUTCString());document.cookie=a+"="+c+"; path=/;"},getCookie:function(a){var b,d,e,f=document.cookie.split(";");for(b=0;b<f.length;b++)if(d=f[b].substr(0,f[b].indexOf("=")),e=f[b].substr(f[b].indexOf("=")+1),d=d.replace(/^\s+|\s+$/g,""),d==a)return unescape(e);return null},switchType:function(){var b=this;this.hide(function(){b.type="android"==b.type?"ios":"android";
var c=a("android"==b.type?'meta[name="google-play-app"]':'meta[name="apple-itunes-app"]').attr("content");b.appId=/app-id=([^\s,]+)/.exec(c)[1];a("#smartbanner").detach();b.create();b.show()})}};a.smartbanner=function(b){var c=a(window),d=c.data("typeahead");d||c.data("typeahead",d=new g("object"==typeof b&&b));if("string"==typeof b)d[b]()};a.smartbanner.defaults={title:null,author:null,price:"FREE",appStoreLanguage:"us",inAppStore:"On the App Store",inGooglePlay:"In Google Play",inWindowsStore:"In the Windows Store",
icon:null,iconGloss:null,button:"VIEW",url:null,scale:"auto",speedIn:300,speedOut:400,daysHidden:15,daysReminder:90,force:null};a.smartbanner.Constructor=g}(window.jQuery);
