var $jscomp={scope:{},findInternal:function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6-impl","es3");var Sputnik=Sputnik||{};
if("1"!=getCookie("sputnik_privacy_policy")||void 0==getCookie("sputnik_privacy_policy")){var btnCookie=document.getElementById("cookieAccept"),containerCookie=document.getElementById("cookieContainer");null!==containerCookie&&void 0!==containerCookie&&(containerCookie.className+=" m-active",btnCookie.addEventListener("click",function(a){a.preventDefault();setCookie("sputnik_privacy_policy","1",63072E6,"/");containerCookie.style.display="none"}));"object"===typeof Stickyfill&&null!==containerCookie&&
void 0!==containerCookie&&Stickyfill.add(containerCookie)}$.extend(Sputnik,{radioWindow:null,setRadioWindow:function(a){this.radioWindow&&this.radioWindow.close();this.radioWindow=window.open(a,"sputnikradiowindow","width=1059, height=273, resizable=no, fullscreen=no");return this}});$.fn.nextOrFirst=function(a){var c=this.next(a);return c.length?c:this.prevAll(a).last()};$.fn.prevOrLast=function(a){var c=this.prev(a);return c.length?c:this.nextAll(a).last()};
function html5videoFunctions(a){a=$("#"+a);var c=$("video",a),b=$(".play_button",a),d=$(".html5video_end",a);b.click(function(){c.get(0).play();b.hide()});c.bind("playing",function(){d.fadeOut();b.hide()}).bind("pause",function(){b.show()}).bind("ended",function(){d.fadeIn();b.hide()})}var currlist=$("#currlist");setInterval(function(){currlist.find("li.b-show").removeClass("b-show").nextOrFirst("li").addClass("b-show")},3E3);
$(function(){$(".b-slider").each(function(){if(1<$(this).find("li").length){var a=0,c=Sputnik.rtl?!0:!1,b=$(this).find(".b-slider__list").lightSlider({item:1,adaptiveHeight:!0,speed:300,controls:!1,gallery:!1,pager:!1,rtl:c,onAfterSlide:function(b,c){a=c}}),d=$(this).find("li").length;$(this).find(".arrow-holder.left").on("click",function(){b.goToSlide(0==a?d-1:a-1)});$(this).find(".arrow-holder.right").on("click",function(){b.goToSlide(a==d-1?0:a+1)})}else $(this).find(".arrow-holder").hide()})});
$(function(){$.ajax({url:"/services/navigator/main.json",dataType:"json"}).done(function(a){var c='<ul class="b-sitenav-all__list">',b=Math.ceil(a.data.length/3),d,e,f;if(a.data){for(d in a.data){e=a.data[d].title;f=a.data[d].url;id=a.data[d].id;0===d%b&&0<d&&(c+='</ul><ul class="b-sitenav-all__list">');var g="";f==Sputnik.www&&(g=' class="current"');attrID=' id="id-'+id+'"';c+="<li"+g+attrID+'><a href="'+f+'">'+e+"</a></li>"}c+="</ul>";$("#sitenavAll").html(c)}});$(".b-sitenav-all__trigger").on("click",
function(a){a.preventDefault();$(".b-sitenav-all").slideToggle()})});
$(function(){$("#mainnav").on("click",".b-mainnav__control",function(){$(".b-mainnav__list").slideToggle()}).on("mouseenter",".b-mainnav__list a",function(){var a=$(this),c;a.closest("li").addClass("active").siblings("li").removeClass("active");$(".b-mainnav__2level").removeClass("active").filter(a.attr("data-for")).addClass("active");c=$(".b-mainnav__2level-list:visible:not(.m-positioned)");c.length&&(a=parseInt(a.offset().left+a.innerWidth()-c.offset().left-c.width()),0<a&&c.css("marginLeft",a).addClass("m-positioned"))}).on("mouseleave",
function(){$(this).find(".active").removeClass("active")});$(".b-navbutton").on("click",function(a){$(".b-mainnav__list, .b-header__nav").slideToggle(function(){$(this).hasClass("navclosed")&&$(this).css("display","");$(this).toggleClass("navclosed")})})});
$(function(){if($(".b-lang-switcher").length)$(".b-lang-switcher .selected").on("click",function(){var a=$(this).data("position");$("#js-lang-switcher_"+a).toggleClass("active");$(".b-lang-switcher .b-lang-switcher__list span").on("click",function(){$("#js-lang-switcher_"+a).toggleClass("active")});$(document).on("click",function(c){0===$(".b-lang-switcher").has(c.target).length&&$("#js-lang-switcher_"+a).removeClass("active")})})});
$(function(){var a=$(".b-header__nav-search");a.on("click","a",function(c){c.preventDefault();c.stopPropagation();a.find(".b-header__nav-form-text").trigger("focus");a.addClass("m-search-open");$(document).on("click.nav-search",function(){a.removeClass("m-search-open");$(document).off("click.nav-search")})}).on("click",".b-header__nav-form",function(a){a.stopPropagation()})});
$(function(){$(".js-openRadio").on("click",function(){var a;a=void 0!==$(this).data("locale")&&void 0!==$(this).data("ssl")?"https://sputniknews.com/popup_radio/"+$(this).data("locale")+"/"+$(this).data("ssl"):"/popup/radio/";$(".responsive").length&&$(".touch").length&&$(".b-header__nav-radio-play").hasClass("js-popup")?Sputnik.setRadioWindow(a):$(".responsive").length&&$(".touch").length?window.open($(this).data("url"),"_blank"):Sputnik.setRadioWindow(a)});$(".b-tabs__head").on("click","a",function(a){a.preventDefault();
a=$(this);a.closest(".b-tabs__head-item").addClass("active").siblings(".b-tabs__head-item").removeClass("active").closest(".b-tabs").find(a.attr("href")).addClass("active").siblings(".b-tabs__content").removeClass("active")});$(window).scroll(function(){500<$(this).scrollTop()?$(".arrowup").fadeIn():$(".arrowup").fadeOut()});$(".arrowup").on("click",function(){$("html, body").animate({scrollTop:0},800);return!1});var a;if($("#share").length){var c=function(){$(window).scrollTop()>e&&$(window).scrollTop()<
f?$(".social-likes-pane").addClass("social-likes-pane__fixed"):$(".social-likes-pane").removeClass("social-likes-pane__fixed")},b=function(){return 100<$(".social-likes-pane").width()?$(".social-likes-pane__holder").offset().top-$(window).height()+$("#share").height():$("body").height()},d=function(){return 100>$(".social-likes-pane").width()?$(".b-breakingnews").length?$(".b-breakingnews").offset().top+143:208:$(".b-article").length?$(".b-article").offset().top-$(window).height()+$("#share").height()+
130:$(".b-article__vote-content").length?$(".b-article__vote-content").offset().top-$(window).height()+$("#share").height()+30:$(".social-likes-pane__holder").offset().top};socialLikesButtons={facebook:{counters:!1,click:function(a){FB.ui({method:"share",href:$("meta[property=og\\:url]").attr("content")||location.href},function(a){a&&!a.error_message&&$.get("/services/share_article/?article_id="+GLOBAL.article.id+"&network=facebook")})}},reddit:{popupUrl:"https://www.reddit.com/submit?url={url}",
popupWidth:650,popupHeight:500},tumblr:{popupUrl:"https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}",popupWidth:540,popupHeight:600},stumbleupon:{popupUrl:"http://www.stumbleupon.com/submit?url={url}",popupWidth:650,popupHeight:500},blogger:{popupUrl:"https://www.blogger.com/blog-this.g?u={url}",popupWidth:650,popupHeight:500},linkedin:{popupUrl:"https://www.linkedin.com/shareArticle?mini=true&url={url}",popupWidth:650,popupHeight:500},netvibes:{popupUrl:"http://www.netvibes.com/subscribe.php?url="+
Sputnik.www+"export/rss2/archive/index.xml",popupWidth:820,popupHeight:500},meneame:{popupUrl:"https://www.meneame.net/submit.php?url={url}",popupWidth:820,popupHeight:500},hatena:{counterUrl:"http://api.b.st-hatena.com/entry.count?url={url}",popupUrl:"http://b.hatena.ne.jp/entry/{url}",popupWidth:820,popupHeight:500},line:{popupUrl:"http://line.me/R/msg/line/?{title} {url}",popupWidth:820,popupHeight:500},naver:{popupUrl:"http://share.naver.com/web/shareView.nhn?url={url}&title={title}",popupWidth:820,
popupHeight:500},telegram:{popupUrl:"https://telegram.me/share/url?url={url}",popupWidth:820,popupHeight:500},whatsapp:{popupUrl:"whatsapp://send?text={url}",popupWidth:820,popupHeight:500},viber:{popupUrl:"viber://forward?text={url}",popupWidth:820,popupHeight:500},weibo:{popupUrl:"http://service.weibo.com/share/share.php?url={url}&title={title}&type=button&language=zh_cn",popupWidth:820,popupHeight:500}};$("#share").socialLikes({forceUpdate:!0});$(".social-likes-pane__etc-link").on("click",function(){$(".social-likes-pane__etc-popup").addClass("visible");
$("#share .social-likes-pane__etc-popup").socialLikes()});$(".social-likes-pane__etc-close").on("click",function(){$(".social-likes-pane__etc-popup").removeClass("visible")});$("#share").on("popup_opened.social-likes",function(){$(".social-likes-pane__etc-popup").removeClass("visible")});$(".js-anchor").on("click",function(a){a.preventDefault();a=$("[data-name="+$(this).data("anchor")+"]");console.log(a,$(this).data("anchor"));a.length&&$("html, body").animate({scrollTop:a.offset().top},300)});var e=
d(),f=b();c();$(window).load(function(){e=d();f=b();c()});$(window).resize(function(){clearTimeout(a);a=setTimeout(function(){e=d();f=b();c()},100)});$(window).scroll(function(){c()});$("#share").on("popup_closed.social-likes",function(a,b){GLOBAL&&GLOBAL.article&&GLOBAL.article.id&&$.get("/services/share_article/?article_id="+GLOBAL.article.id+"&network="+b)});$(".social-likes-pane__wechat").on("click",".social-likes__icon",function(a){a.preventDefault();a.stopPropagation();var b=$(this).closest(".social-likes-pane__wechat").find(".social-likes__share");
b.fadeToggle();if(!b.find("svg").length&&"object"===typeof qrcodegen){a=b.data("href");var c=qrcodegen.QrCode;a=c.encodeText(a,c.Ecc.MEDIUM).toSvgString(4);b.append(a)}$(document).on("click.social-wechat",function(){b.fadeOut();$(document).off("click.social-wechat")})})}if($(".responsive").length&&"undefined"!=typeof window.matchMedia){var g=function(a){a.matches?($(".b-sitenav .b-header__nav-search").length||$(".b-header__nav-search").appendTo($(".b-sitenav > .l-wrap")),$(".b-header__nav .b-userpanel").length||
$(".b-userpanel").appendTo($(".b-header__nav > .l-wrap")),$(".m-sidebar-move").length&&$(".b-news").appendTo($(".b-article")),$(".l-maincolumn .b-cal").length||$(".b-cal").insertAfter($(".l-maincolumn .b-more"))):($(".b-header__nav .b-header__nav-search").length||$(".b-header__nav-search").appendTo($(".b-header__nav > .l-wrap")),$(".b-sitenav__time .b-userpanel").length||$(".b-userpanel").prependTo($(".b-sitenav__time")),$(".m-sidebar-move").length&&$(".b-news").appendTo($(".l-sidebar").eq(0)),$(".footer .b-cal").length||
$(".b-cal").insertBefore($(".footer__nav")))};window.matchMedia("(max-width: 479px)");var h=window.matchMedia("(max-width: 767px)");window.matchMedia("(max-width: 1023px)");matchMedia&&(h.addListener(g),g(h));$(".b-profile__tabs").lightSlider({autoWidth:!0,slideMargin:0,speed:100,controls:!0,gallery:!1,pager:!1,rtl:Sputnik.rtl,onSliderLoad:function(a){a.goToSlide($(".b-profile__tabs").find("li.m-active").index())}})}$(".b-news-stripe__head").on("click","a",function(a){a.preventDefault();a=$(this);
a.closest("li").addClass("active").siblings("li").removeClass("active").closest(".b-news-stripe").find(a.attr("href")).addClass("active").siblings(".b-news-stripe__list").removeClass("active")});$(".js-likes").on("click","a",function(a){a.preventDefault();var b=$(this);a=b.attr("href");var c=b.closest(".js-likes");$.ajax({url:a,type:"post"}).done(function(a){a=$.parseJSON($.trim(a));b.toggleClass("active").siblings("span").removeClass("active");c.find(".js-likeUp").html(a.likes);c.find(".js-likeDown").html(a.dislikes)})});
$(".b-vote__form").on("click",".b-vote__form-item",function(){$(this).find(":checkbox").length?$(this).find(":checked").length?$(this).addClass("active"):$(this).removeClass("active"):$(this).addClass("active").siblings().removeClass("active")}).on("submit",function(a){a.preventDefault();var b,c=$(this),d=JSON.parse(localStorage.getItem("Vote"))||[];b=c.find('input[name="article_id"]').val();$.ajax({url:c.attr("action"),data:c.serialize(),dataType:"html"}).done(function(a){c.replaceWith(a);0>$.inArray(b,
d)&&(99<d.length&&d.pop(),d.unshift(b),localStorage.setItem("Vote",JSON.stringify(d)))})});$(".b-more").on("click",".b-btn",function(a){a.preventDefault();var b=$(this),c=$("."+b.data("for")).eq(0);a=b.data("href");b.hasClass("disabled")||$.ajax({url:a,type:"get",dataType:"html",context:document,beforeSend:function(){b.addClass("disabled")},complete:function(){b.removeClass("disabled")}}).done(function(a){var d="b-plainlist"===b.data("for")?"&list_type=plainlist":"";a=0<a.indexOf("html")&&0<a.indexOf("body")?
$(a).contents():$(a);var e=(c.children("ul").length?c.children("ul"):c).append(a).trigger("more:load").children().last().data("next"),e=e+d;a.filter("li").hasClass("b-author__item")&&10>a.filter("li").length&&(e=!1);e?b.data("href",e):b.remove()})})});
$(function(){function a(a){var b=document;a=b.getElementById(a);var c;b.body.createTextRange?(b=document.body.createTextRange(),b.moveToElementText(a),b.select()):window.getSelection&&(c=window.getSelection(),b=document.createRange(),b.selectNodeContents(a),c.removeAllRanges(),c.addRange(b))}$("body").on("click","#getShortUrl",function(c){c.preventDefault();var b=$(this);b.data("shorturl")?(b.addClass("m-open").html(b.data("shorturl")),a("getShortUrl"),$("#getShortUrl").off("click")):$.ajax({url:"/services/get_short_link/?article_id="+
b.data("article"),dataType:"text"}).done(function(c){b.addClass("m-open").html($.trim(c));a("getShortUrl");$("#getShortUrl").off("click")})});$.smartbanner instanceof Function&&!/(iPad|iPhone|iPod).*OS [6-7].*AppleWebKit.*Mobile.*Safari/.test(navigator.userAgent)&&("http://sputniknews.cn/"===Sputnik.www?$.smartbanner({title:"\u4fc4\u7f57\u65af\u536b\u661f\u901a\u8baf\u793e",price:"\u624b\u673a\u5ba2\u6237\u7aef",inAppStore:"",inGooglePlay:"",author:" ",button:"\u70b9\u51fb\u4e0b\u8f7d",url:"http://sputniknews.cn/docs/products/mobile.html"}):
"http://big5.sputniknews.cn/"===Sputnik.www?$.smartbanner({title:"\u4fc4\u7f85\u65af\u885b\u661f\u901a\u8a0a\u793e",price:"\u624b\u6a5f\u5ba2\u6236\u7aef",inAppStore:"",inGooglePlay:"",author:" ",button:"\u9ede\u64ca\u4e0b\u8f09",url:"http://big5.sputniknews.cn/docs/products/mobile.html"}):$.smartbanner({title:"Sputnik News"}));SputnikSNG&&(document.body.oncopy=function(){var a=window.getSelection(),b=a.getRangeAt(0);if(!/^https?\:\/\/sptnkne\.ws\/\S\w*$/.test($.trim(a))&&!$(b.startContainer).hasClass("video-share")){var d=
b.cloneContents(),e=$("link[rel='canonical']").attr("href")||window.location.protocol+"//"+window.location.hostname+window.location.pathname,e="<br /><br />"+(""==Sputnik.locale.readmore?"Read more: ":Sputnik.locale.readmore)+": <a href='"+e+"'>"+e+"</a>",f=$("<div>").append(d).append(e);$("body").append(f);a.selectAllChildren(f[0]);window.setTimeout(function(){a.removeAllRanges();a.addRange(b);f.remove()},0)}})});
$(function(){var a=$(".b-news-stripe").find(".touchcarousel");a.each(function(a,b){var c=$(this),e,f;c.find("a").addClass("non-draggable");e=c.touchCarousel({pagingNav:!1,snapToItems:!0,itemsPerMove:4,scrollbar:!1,transitionSpeed:300,loopItems:!0,dragUsingMouse:!1}).data("touchCarousel");f=c.find(".touchcarousel-item");Sputnik.rtl&&e.goTo(f.length-1);f.addClass("m-touch");c.show()});$(".b-news-stripe__flipper").on("click",function(){var c=$(this).data("dir");"next"===c&&a.filter(":visible").data("touchCarousel").next();
"prev"===c&&a.filter(":visible").data("touchCarousel").prev()})});(function(a){var c=a(".captcha-image").filter(":visible");Sputnik.updateCaptcha=function(b){b=b||a(".captcha-image");b.attr("src","/services/captcha/?"+(new Date).getTime())};a("body").on("click",".captcha-refresh",function(){Sputnik.updateCaptcha()});Sputnik.updateCaptcha(c)})(jQuery);
(function(a){a(".footer__text").length&&"function"===typeof a.fn.jScrollPane&&a(".footer__text").jScrollPane({verticalDragMinHeight:20,verticalDragMaxHeight:20,horizontalDragMinWidth:20,horizontalDragMaxWidth:20})})(jQuery);$(function(){if($(".fb-comment-counter").length){var a=$(".fb-comment-counter").data("href");$.ajax({url:"https://graph.facebook.com/v2.7/",dataType:"jsonp",type:"GET",data:{access_token:"666987483466439|b3e1a0948513223b0bc51b32a735e2cf",id:a},success:function(a){$(".fb-comment-counter").text(a.share.comment_count)}})}});
(function(a){a(".b-header__nav-form-text").length&&(a(".b-header__nav-form-text").attr("autocorrect","off"),a(".b-header__nav-form-text").attr("autocapitalize","off"))})(jQuery);(function(a){a("#orbit-slider").lightSlider({item:1,adaptiveHeight:!0,slideMove:1,speed:300})})(jQuery);
(function(a){function c(b){a(window).resize(function(){var a;a=b.parent().width()>b.attr("width")?b.attr("width"):b.parent().width();b.width(a).height(a*b.attr("data-ratio"))}).resize()}a(".adaptive-iframe").on("load",function(){var b=a(this);b.attr("data-ratio",b.attr("height")/b.attr("width"));c(b);b.removeClass("m-inject-hidden")});a(".b-article__text iframe").each(function(){var b=a(this);0<=b.attr("src").indexOf("facebook.com/plugins/video.php")&&!b.hasClass("adaptive-iframe")&&(b.attr("data-ratio",
b.attr("height")/b.attr("width")).addClass("adaptive-iframe"),c(b))})})(jQuery);
(function(a){var c=Sputnik.rtl?!0:!1,b=a(".b-main-slider");b.length&&"function"===typeof a.fn.owlCarousel&&(b.on("mouseover",function(c){a(c.target).closest(".owl-nav").length||a(c.target).closest(".owl-dots").length||a(c.target).closest(".b-main-slider__content").length?b.addClass("hover"):b.removeClass("hover")}).on("mouseleave",function(a){b.removeClass("hover")}),b.owlCarousel({autoplay:!0,loop:!0,margin:0,nav:!0,items:1,dots:!0,touchDrag:!1,mouseDrag:!1,rtl:c,animateIn:"fadeIn",animateOut:"fadeOut"}))})(jQuery);
(function(a){a(".b-header__nav-social-item.wechat").on("click",function(c){c.preventDefault();c.stopPropagation();var b=a(this).closest(".b-header__nav-social-item").find(".b-header__nav-social-modal");b.is(":visible")?(b.fadeOut(300),a(document).off("click.social-modal")):(b.fadeIn(300),a(document).on("click.social-modal",function(){b.fadeOut(300);a(document).off("click.social-modal")}))})})(jQuery);
(function(a){a(".b-header__nav-social-item.wechat").on("click",function(c){c.preventDefault();c.stopPropagation();var b=a(this).closest(".b-header__nav-social-item").find(".b-header__nav-social-modal");b.is(":visible")?(b.fadeOut(300),a(document).off("click.social-modal")):(b.fadeIn(300),a(document).on("click.social-modal",function(){b.fadeOut(300);a(document).off("click.social-modal")}))})})(jQuery);
(function(a){var c=a("#inread_container");a=a("#inread_banner");var b=a.removeClass("hide");c.length&&a.length&&(a.remove(),c.append(b.children()))})(jQuery);document.addEventListener("DOMContentLoaded",function(a){"function"===typeof lazyload&&lazyload()});
