var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=
!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{var b;a:switch(typeof a){case "object":b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==
typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),
a[b]=null;this.onSettledCallbacks_=null}};var e=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(l){g(l)}}:b}var e,g,f=new c(function(a,b){e=a;g=b});this.callWhenSettled_(d(a,e),
d(b,g));return f};c.prototype["catch"]=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?e.asyncExecute(c):this.onSettledCallbacks_.push(function(){e.asyncExecute(c)})};c.resolve=function(a){return a instanceof c?a:new c(function(b,c){b(a)})};c.reject=function(a){return new c(function(b,c){c(a)})};
c.race=function(a){return new c(function(b,d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c.resolve(f.value).callWhenSettled_(b,d)})};c.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c.resolve([]):new c(function(a,e){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c.resolve(d.value).callWhenSettled_(f(g.length-1),e),d=b.next();while(!d.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(c.$jscomp$new$AsyncExecutor=function(){return new b});
return c},"es6-impl","es3");var endpoint,key,authSecret,browser,pushStatus=!1,trackingId="",domain="undefined"!==typeof domain?domain:document.domain;
$(function(){function a(b){"default"===b.permission&&GLOBAL&&GLOBAL.locale.id&&GLOBAL.locale.id.project_id&&GLOBAL.locale.id.project_name?(console.log("Push default"),window.safari.pushNotification.requestPermission("https://"+GLOBAL.locale.id.domain+"/applepush",GLOBAL.locale.id.project_id,{project:GLOBAL.locale.id.project_name},a)):"denied"===b.permission?console.log("Push no"):"granted"===b.permission&&console.log("Push yes")}if("safari"in window&&"pushNotification"in window.safari&&GLOBAL&&GLOBAL.locale.id&&
GLOBAL.locale.id.project_id){var b=window.safari.pushNotification.permission(GLOBAL.locale.id.project_id);a(b)}if("serviceWorker"in navigator){browser=push_getUserAgent();if("chrome"!=browser&&"firefox"!=browser)return!1;(b=push_getCookie("_push"))||"default"!=Notification.permission?b||"granted"!=Notification.permission||push_getStatus(function(a){!1===a?push_checkTrueRegister(function(a){!1===a&&push_subscription()}):(push_setCookie("_push",1,2592E6,"/"),console.info("Push is subs"))}):(push_subscription(),
push_setCookie("_checkpush",1,31104E6,"/"))}else console.log("Don't supported SW")});function push_sendMessage(a){return new Promise(function(b,d){var c=new MessageChannel;c.port1.onmessage=function(a){a.data.error?d(a.data.error):b(a.data)};navigator.serviceWorker.controller.postMessage(a,[c.port2])})}
function push_checkTrueRegister(a){navigator.serviceWorker.register("/sw.js?9").then(function(b){return b.pushManager.getSubscription().then(function(a){var b=a.getKey?a.getKey("p256dh"):"",b=b?btoa(String.fromCharCode.apply(null,new Uint8Array(b))):"",d=a.getKey?a.getKey("auth"):"",d=d?btoa(String.fromCharCode.apply(null,new Uint8Array(d))):"";a=a.endpoint.split("/").slice(-1)[0];fetch("/web_push/register/",{method:"post",headers:{"Content-type":"application/x-www-form-urlencoded; charset=UTF-8"},
body:"endpoint="+a+"&key="+b+"&auth_secret="+d+"&provider="+browser+"&rereg=1&uid="+push_getVisitorId()})})["catch"](function(b){a&&a(!1,b);console.error("Status error 2",b)})})["catch"](function(b){a&&a(!1,b);console.error("Status error 1",b)})}
function push_subscription(a){navigator.serviceWorker.register("/sw.js?9").then(function(b){return b.pushManager.getSubscription().then(function(d){if(!d)return push_setCookie("_push",1,2592E6,"/",domain),b.pushManager.subscribe({userVisibleOnly:!0}).then(function(b){a&&a(!0);return b},function(b){a&&a(!1);console.log(Notification.permission,b);return!1})})}).then(function(a){if(a){var b=a.getKey?a.getKey("p256dh"):"";key=b?btoa(String.fromCharCode.apply(null,new Uint8Array(b))):"";authSecret=(b=
a.getKey?a.getKey("auth"):"")?btoa(String.fromCharCode.apply(null,new Uint8Array(b))):"";endpoint=a.endpoint.split("/").slice(-1)[0];fetch("/web_push/register/",{method:"post",headers:{"Content-type":"application/x-www-form-urlencoded; charset=UTF-8"},body:"endpoint="+endpoint+"&key="+key+"&auth_secret="+authSecret+"&provider="+browser+"&uid="+push_getVisitorId()})}},function(b){a&&a(!1,b);console.error("SW register error...",b)}).then(function(){return navigator.serviceWorker.ready}).then(function(){console.log("send message...")})}
function push_unsubscription(a){navigator.serviceWorker.register("/sw.js?9").then(function(b){b.pushManager.getSubscription().then(function(b){b?b.unsubscribe().then(function(b){a&&a(!0);console.log(b)})["catch"](function(b){a&&a(!1,b);console.log("Unsubscription error: ",b)}):a&&a(!0)})["catch"](function(b){a&&a(!1,b);console.error("Error thrown while unsubscribing from push messaging.",b)})})}
function push_getStatus(a){var b=!1;navigator.serviceWorker.register("/sw.js?9").then(function(d){return d.pushManager.getSubscription().then(function(c){c&&(b=!0);a&&a(b)})["catch"](function(b){a&&a(!1,b);console.error("Status error 2",b)})})["catch"](function(b){a&&a(!1,b);console.error("Status error 1",b)});return b}
function push_getUserAgent(){var a=navigator.userAgent,b=!1;0<a.search(/MSIE/)&&(b="ie");0<a.search(/Firefox/)&&(b="firefox");0<a.search(/Opera/)&&(b="opera");0<a.search(/Chrome/)&&(b="chrome");0<a.search(/Safari/)&&(b="safari");0<a.search(/YaBrowser/)&&(b="chrome");window.chrome&&(b="chrome");return b}
function push_setCookie(a,b,d,c,e,g){var f;d&&(f=new Date,f.setTime(f.getTime()+d));document.cookie=a+"="+b+(d?";expires="+f.toGMTString():"")+";path="+(c||"/")+(e?";domain="+e:"")+(g?";secure":"")}function push_getCookie(a){return(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(document.cookie))?decodeURIComponent(a[2]):0}function push_getVisitorId(){var a=null;objPWConfig&&"get"in objPWConfig&&(a=objPWConfig.get("visitor_id"));return a};
