'use strict';function init_audio_player(player_id,file_url){jQuery('#jquery_jplayer_'+player_id).jPlayer({ready:function(event){jQuery(this).jPlayer('setMedia',{mp3:file_url});},play:function(){jQuery('.jp-jplayer').not(this).jPlayer('stop');},swfPath:'/wp-content/themes/nknews/images',supplied:'mp3',useStateClassSkin:true,preload:'none',cssSelectorAncestor:'#jp_container_'+player_id});}
(function($){if($('#headerSlider').length>0){$('#headerSlider').slick({autoplay:true,autoplaySpeed:4000,arrows:false,dots:true,lazyLoad:'ondemand',fade:true,cssEase:'linear',appendDots:'#newsSliderDots'});}
if($('#moreNewsSlider').length>0){$('#moreNewsSlider').slick({slidesToScroll:2,autoplaySpeed:5000,arrows:false,dots:false,variableWidth:true,responsive:[{breakpoint:768,settings:{slidesToScroll:1}}]});}
if(jQuery('body').hasClass('home')){var ajaxRunning=false;jQuery(window).scroll(function(){var diff=jQuery(document).height()-
jQuery(window).height()-
jQuery(window).scrollTop();if(!ajaxRunning&&diff<160){ajaxRunning=true;var post_offset=jQuery('.singleHeadlinePostWrapper').children().length+2;jQuery.ajax({url:'/wp-admin/admin-ajax.php',type:'post',data:{action:'get_featured_posts',offset:post_offset},success:function(result){if(result.length>0){jQuery('.singleHeadlinePostWrapper').append(result);ajaxRunning=false;}else{jQuery('#newsLoader>span').html('No more posts!');}}});}});}
if($('#moreNewsArrow').length>0){$('body').on('click','#moreNewsArrow',function(){$('#moreNewsSlider').slick('slickNext');});}
function getParameterByName(name,url){if(!url)url=window.location.href;name=name.replace(/[\[\]]/g,'\\$&');var regex=new RegExp('[?&]'+name+'(=([^&#]*)|&|#|$)'),results=regex.exec(url);if(!results)return null;if(!results[2])return '';return decodeURIComponent(results[2].replace(/\+/g,' '));}
Stickyfill.add($('.sticky'));$(window).on('load',function(){const body=$('body');let offset=body.hasClass('home')?100:0;jQuery('#header-top').headroom({offset:offset,tolerance:20,classes:{pinned:'htop--pinned',unpinned:'htop--unpinned'}});if(window.innerWidth>992){$('body.single .sticky_widget, body.page .sticky_widget, body.category .sticky_widget, body.archive .sticky_widget').sticky({topSpacing:120,bottomSpacing:function(){if($('#fake_end_point').length===0)return 0;return($('html').height()-
($('#fake_end_point').offset().top-40));}});}
if(!$('#main-navigation').is(':visible')){jQuery('#mobile-header').headroom({offset:70,tolerance:20,classes:{pinned:'mHead--pinned',unpinned:'mHead--unpinned'}});}
offset=body.hasClass('home')?460:70;$('#main-navigation').headroom({offset:offset,tolerance:20,classes:{pinned:'dmenu--pinned',unpinned:'dmenu--unpinned'}});});$(document).ready(function(){$('#scroll_search').change(function(){if(!this.checked)return;$('#search_input').focus();});$('#fullContent table').wrap('<div class="table-responsive"></div>');$('#fullContent table').addClass('table table-bordered');$('#fullContent iframe').wrap('<div class="embed-responsive embed-responsive-16by9"></div>');$('#fullContent iframe').addClass('embed-responsive-item');$('.wp-caption > a').click(function(e){e.preventDefault();});$('.wp-caption-text > a, .image-credit a').attr('target','_blank');$('.stickyElement').sticky({topSpacing:120,getWidthFrom:'.custom-html-widget'});$('#mob_share').on('click',function(){$('#post_share').toggleClass('expand');});$('#post-filter').on('change',function(){window.location.href=$(this).val();});const bd=$('body');bd.on('click','#podcast-close',function(){$('.podcast-body-wrapper').slideToggle(200,'linear',function(){$('#podcast-close i').toggleClass('fa-times fa-chevron-up');});});$('.mobile-menubar').on('click',function(){if(bd.hasClass('mobileMenuActive')){$('#mobile-nav-wrapper').slideToggle(200,'swing',function(){bd.removeClass('mobileMenuActive');});}else{bd.addClass('mobileMenuActive');$('#mobile-nav-wrapper').slideToggle(200,'swing');}});$('.mobile-nav-links').on('click','a',function(e){if($(this).next('.dropdownlist').length){e.preventDefault();if($(this).parent().hasClass('open-navlist')){$(this).parent().removeClass('open-navlist');}else{$('.mobile-nav-links li.open-navlist').removeClass('open-navlist');$(this).parent().addClass('open-navlist');}
if($(this).next('.dropdownlist').hasClass('active')){$('.dropdownlist.active').removeClass('active').slideUp(200);}else{$('.mobile-nav-links .dropdownlist.active').slideUp(200).removeClass('active');$(this).next('.dropdownlist').addClass('active').slideDown(200);}}});$('.switch_popop').on('click',function(){$('#'+$(this).data('from')).modal('hide');$('#'+$(this).data('to')).modal('show');});if(typeof getParameterByName('popup')=='string'&&getParameterByName('popup').length>0){$('#'+getParameterByName('popup')).modal('show');}
$('#signin').on('shown.bs.modal',function(){const mw=$('#mobile-nav-wrapper');if(mw.is(':visible')){mw.slideUp(200,'swing',function(){$('body').removeClass('mobileMenuActive');});}});$('#fullContent table').addClass('table table-bordered');$('.step_one').on('click',function(){const email_add=$(this).parent().find('.email_address').val();if(email_add.length===0)return false;const re=/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;const is_email=re.test(email_add);if(!is_email)return false;$(this).parent().removeClass('d-flex').addClass('d-none').next().removeClass('d-none');});if(typeof main_script_callback==='function'){main_script_callback();}
if($('body').hasClass('single')){$('#fullContent img[class*="wp-image-"]').click(function(){if($(this).closest('.wp-caption').length){lity(this.src);}});}});})(jQuery);